### ISSUE TITLE
Fix non working `gitpod-start`

### ISSUE THREAD

**Issue by FreePhoenix888** [deep-foundation/dev#109]
Current command output:

```
gitpod /workspace/dev (main) $ npm run gitpod-start

> @deep-foundation/dev@0.0.21 gitpod-start /workspace/dev
> export NEXT_PUBLIC_ENGINES=0; export NEXT_PUBLIC_HIDEPATH=1; export npm_config_yes=true; export JWT_SECRET="{\"type\":\"HS256\",\"key\":\"3EK6FD+o0+c7tzBNVfjpMkNDi2yARAAKzQlk8O2IKoxQu4nF7EdAh8s3TwpHwrdWT6R\"}" export MIGRATIONS_ID_TYPE_SQL=bigint; export MIGRATIONS_ID_TYPE_GQL=bigint; export MIGRATIONS_HASURA_PATH=$(echo $(gp url 8080) | awk -F[/:] '{print $4}'); export DEEPLINKS_HASURA_PATH=$(echo $(gp url 8080) | awk -F[/:] '{print $4}'); export MIGRATIONS_HASURA_SSL=1; export DEEPLINKS_HASURA_SSL=1; export MIGRATIONS_HASURA_SECRET=myadminsecretkey; export DEEPLINKS_HASURA_SECRET=myadminsecretkey;  export NEXT_PUBLIC_DEEPLINKS_SERVER=https://$(echo $(gp url 3007) | awk -F[/:] '{print $4}'); export NEXT_PUBLIC_GQL_PATH=$(echo $(gp url 3006) | awk -F[/:] '{print $4}')/gql; export NEXT_PUBLIC_GQL_SSL=1 DEEPLINKS_HASURA_PATH=$(echo $(gp url 8080) | awk -F[/:] '{print $4}'); export DEEPLINKS_HASURA_SSL=1; export MIGRATIONS_DEEPLINKS_APP_URL=$(gp url 3007); export MIGRATIONS_DEEPLINKS_URL=$(gp url 3006); export DEEPLINKS_PUBLIC_URL=$(gp url 3006); export DOCKER_DEEPLINKS_URL=http://host.docker.internal:3006; export DEEPLINKS_ROUTE_HANDLERS_HOST=host.docker.internal; npm run gitpod-hasura-reattach; concurrently "npm run deepcase" "npm run deeplinks" "npm run gitpod-engine" "npm run nextjs"

npm WARN cli npm v9.3.0 does not support Node.js v14.15.0. You should probably upgrade to a
npm WARN cli newer version of node as we can't make any promises that npm will work with this
npm WARN cli version. This version of npm supports the following node versions: `^14.17.0 ||
npm WARN cli ^16.13.0 || >=18.0.0`. You can find the latest version at https://nodejs.org/.
npm WARN config cache-min This option has been deprecated in favor of `--prefer-offline`.
npm WARN config cache-max This option has been deprecated in favor of `--prefer-online`
npm WARN config tmp This setting is no longer used.  npm stores temporary files in a special
npm WARN config location in the cache, and they are managed by
npm WARN config     [`cacache`](http://npm.im/cacache).
npm WARN config shrinkwrap Use the --package-lock setting instead.
npm WARN config optional Use `--omit=optional` to exclude optional dependencies, or
npm WARN config `--include=optional` to include them.
npm WARN config 
npm WARN config     Default value does install optional deps unless otherwise omitted.

> @deep-foundation/dev@0.0.21 gitpod-hasura-reattach
> export REATTACH_HASURA_SECRET=myadminsecretkey; export REATTACH_HASURA_PATH=$(echo $(gp url 8080) | awk -F[/:] '{print $4}'); export REATTACH_HASURA_SSL=1; export REATTACH_DEEPLINKS_PATH=$(echo $(gp url 3006) | awk -F[/:] '{print $4}'); npx gulp gitpod:hasura:reattach

npm WARN cli npm v9.3.0 does not support Node.js v14.15.0. You should probably upgrade to a
npm WARN cli newer version of node as we can't make any promises that npm will work with this
npm WARN cli version. This version of npm supports the following node versions: `^14.17.0 ||
npm WARN cli ^16.13.0 || >=18.0.0`. You can find the latest version at https://nodejs.org/.
npm WARN config cache-min This option has been deprecated in favor of `--prefer-offline`.
npm WARN config cache-max This option has been deprecated in favor of `--prefer-online`
npm WARN config tmp This setting is no longer used.  npm stores temporary files in a special
npm WARN config location in the cache, and they are managed by
npm WARN config     [`cacache`](http://npm.im/cacache).
npm WARN config shrinkwrap Use the --package-lock setting instead.
npm WARN config optional Use `--omit=optional` to exclude optional dependencies, or
npm WARN config `--include=optional` to include them.
npm WARN config 
npm WARN config     Default value does install optional deps unless otherwise omitted.
[19:23:54] Requiring external module ts-node/register
=============================================
simple-git has supported promises / async await since version 2.6.0.
 Importing from 'simple-git/promise' has been deprecated and will
 report this error until the next major release of version 4.

To upgrade, change all 'simple-git/promise' imports to just 'simple-git'
=============================================
[19:23:57] Using gulpfile /workspace/dev/gulpfile.ts
[19:23:57] Starting 'gitpod:hasura:reattach'...
3006-deepfoundation-dev-htv9uitbiie.ws-eu82.gitpod.io
remote_schemas undefined
actions [
  {
    name: 'reserve',
    definition: {
      handler: 'http://host.docker.internal:3006/api/reserved',
      output_type: 'reserveResponse',
      forward_client_headers: true,
      arguments: [Array],
      type: 'mutation',
      kind: 'synchronous'
    },
    permissions: [ [Object] ]
  }
]
a http://host.docker.internal:3006/api/reserved
error Bad Request {
  path: '$.args',
  error: 'action with name "reserve" already exists',
  code: 'already-exists'
}
custom_types { objects: [ { name: 'reserveResponse', fields: [Array] } ] }
cron_triggers [
  {
    name: 'reserved_links_cleaner',
    webhook: 'https://3006-deepfoundation-dev-htv9uitbiie.ws-eu82.gitpod.io///api/reserved-cleaner',
    schedule: '0 * * * *',
    include_in_metadata: true,
    payload: {},
    retry_conf: {
      num_retries: 3,
      timeout_seconds: 120,
      tolerance_seconds: 21675,
      retry_interval_seconds: 12
    },
    comment: 'clean reserved'
  }
]
a https://3006-deepfoundation-dev-htv9uitbiie.ws-eu82.gitpod.io///api/reserved-cleaner
[19:23:59] Finished 'gitpod:hasura:reattach' after 2.26 s
[1] npm WARN cli npm v9.3.0 does not support Node.js v14.15.0. You should probably upgrade to a
[1] npm WARN cli newer version of node as we can't make any promises that npm will work with this
[1] npm WARN cli version. This version of npm supports the following node versions: `^14.17.0 ||
[1] npm WARN cli ^16.13.0 || >=18.0.0`. You can find the latest version at https://nodejs.org/.
[1] npm WARN config cache-min This option has been deprecated in favor of `--prefer-offline`.
[1] npm WARN config cache-max This option has been deprecated in favor of `--prefer-online`
[1] npm WARN config tmp This setting is no longer used.  npm stores temporary files in a special
[1] npm WARN config location in the cache, and they are managed by
[1] npm WARN config     [`cacache`](http://npm.im/cacache).
[1] npm WARN config shrinkwrap Use the --package-lock setting instead.
[1] npm WARN config optional Use `--omit=optional` to exclude optional dependencies, or
[1] npm WARN config `--include=optional` to include them.
[1] npm WARN config 
[1] npm WARN config     Default value does install optional deps unless otherwise omitted.
[0] npm WARN cli npm v9.3.0 does not support Node.js v14.15.0. You should probably upgrade to a
[0] npm WARN cli newer version of node as we can't make any promises that npm will work with this
[0] npm WARN cli version. This version of npm supports the following node versions: `^14.17.0 ||
[0] npm WARN cli ^16.13.0 || >=18.0.0`. You can find the latest version at https://nodejs.org/.
[0] npm WARN config cache-min This option has been deprecated in favor of `--prefer-offline`.
[0] npm WARN config cache-max This option has been deprecated in favor of `--prefer-online`
[0] npm WARN config tmp This setting is no longer used.  npm stores temporary files in a special
[0] npm WARN config location in the cache, and they are managed by
[0] npm WARN config     [`cacache`](http://npm.im/cacache).
[0] npm WARN config shrinkwrap Use the --package-lock setting instead.
[0] npm WARN config optional Use `--omit=optional` to exclude optional dependencies, or
npm WARN config `--include=optional` to include them.
[0] npm WARN config 
[0] npm WARN config     Default value does install optional deps unless otherwise omitted.
[1] 
[1] > @deep-foundation/dev@0.0.21 deeplinks
[1] > cd packages/deeplinks && npm run dev
[1] 
[0] 
[0] > @deep-foundation/dev@0.0.21 deepcase
[0] > (cd packages/deepcase && npm run dev -- -p 3007)
[0] 
[3] npm WARN cli npm v9.3.0 does not support Node.js v14.15.0. You should probably upgrade to a
[3] npm WARN cli newer version of node as we can't make any promises that npm will work with this
[3] npm WARN cli version. This version of npm supports the following node versions: `^14.17.0 ||
[3] npm WARN cli ^16.13.0 || >=18.0.0`. You can find the latest version at https://nodejs.org/.
[3] npm WARN config cache-min This option has been deprecated in favor of `--prefer-offline`.
[3] npm WARN config cache-max This option has been deprecated in favor of `--prefer-online`
[3] npm WARN config tmp This setting is no longer used.  npm stores temporary files in a special
[3] npm WARN config location in the cache, and they are managed by
[3] npm WARN config     [`cacache`](http://npm.im/cacache).
[3] npm WARN config shrinkwrap Use the --package-lock setting instead.
[3] npm WARN config optional Use `--omit=optional` to exclude optional dependencies, or
[3] npm WARN config `--include=optional` to include them.
[3] npm WARN config 
[3] npm WARN config     Default value does install optional deps unless otherwise omitted.
[2] npm WARN cli npm v9.3.0 does not support Node.js v14.15.0. You should probably upgrade to a
npm WARN cli newer version of node as we can't make any promises that npm will work with this
[2] npm WARN cli version. This version of npm supports the following node versions: `^14.17.0 ||
[2] npm WARN cli ^16.13.0 || >=18.0.0`. You can find the latest version at https://nodejs.org/.
[2] npm WARN config cache-min This option has been deprecated in favor of `--prefer-offline`.
[2] npm WARN config cache-max This option has been deprecated in favor of `--prefer-online`
[2] npm WARN config tmp This setting is no longer used.  npm stores temporary files in a special
[2] npm WARN config location in the cache, and they are managed by
[2] npm WARN config     [`cacache`](http://npm.im/cacache).
[2] npm WARN config shrinkwrap Use the --package-lock setting instead.
[2] npm WARN config optional Use `--omit=optional` to exclude optional dependencies, or
npm WARN config `--include=optional` to include them.
[2] npm WARN config 
[2] npm WARN config     Default value does install optional deps unless otherwise omitted.
[3] 
[3] > @deep-foundation/dev@0.0.21 nextjs
[3] > (cd packages/nextjs; PORT=4000 npm run dev)
[3] 
[2] 
[2] > @deep-foundation/dev@0.0.21 gitpod-engine
[2] > cd packages/deeplinks && npm run start-engine-docker
[2] 
[0] npm WARN cli npm v9.3.0 does not support Node.js v14.15.0. You should probably upgrade to a
[0] npm WARN cli newer version of node as we can't make any promises that npm will work with this
[0] npm WARN cli version. This version of npm supports the following node versions: `^14.17.0 ||
npm WARN cli ^16.13.0 || >=18.0.0`. You can find the latest version at https://nodejs.org/.
[0] npm WARN config cache-min This option has been deprecated in favor of `--prefer-offline`.
[0] npm WARN config cache-max This option has been deprecated in favor of `--prefer-online`
[0] npm WARN config tmp This setting is no longer used.  npm stores temporary files in a special
[0] npm WARN config location in the cache, and they are managed by
npm WARN config     [`cacache`](http://npm.im/cacache).
[0] npm WARN config shrinkwrap Use the --package-lock setting instead.
[0] npm WARN config optional Use `--omit=optional` to exclude optional dependencies, or
[0] npm WARN config `--include=optional` to include them.
[0] npm WARN config 
[0] npm WARN config     Default value does install optional deps unless otherwise omitted.
[3] npm WARN cli npm v9.3.0 does not support Node.js v14.15.0. You should probably upgrade to a
[3] npm WARN cli newer version of node as we can't make any promises that npm will work with this
[3] npm WARN cli version. This version of npm supports the following node versions: `^14.17.0 ||
[3] npm WARN cli ^16.13.0 || >=18.0.0`. You can find the latest version at https://nodejs.org/.
[3] npm WARN config cache-min This option has been deprecated in favor of `--prefer-offline`.
[3] npm WARN config cache-max This option has been deprecated in favor of `--prefer-online`
npm WARN config tmp This setting is no longer used.  npm stores temporary files in a special
[3] npm WARN config location in the cache, and they are managed by
[3] npm WARN config     [`cacache`](http://npm.im/cacache).
[3] npm WARN config shrinkwrap Use the --package-lock setting instead.
[3] npm WARN config optional Use `--omit=optional` to exclude optional dependencies, or
[3] npm WARN config `--include=optional` to include them.
[3] npm WARN config 
[3] npm WARN config     Default value does install optional deps unless otherwise omitted.
[0] 
[0] > @deep-foundation/deepcase@0.1.0-beta.2 dev
[0] > next dev -p 3007
[0] 
[3] 
[3] > @deep-foundation/nextjs@0.0.0 dev
[3] > next dev
[3] 
[1] npm WARN cli npm v9.3.0 does not support Node.js v14.15.0. You should probably upgrade to a
[1] npm WARN cli newer version of node as we can't make any promises that npm will work with this
[1] npm WARN cli version. This version of npm supports the following node versions: `^14.17.0 ||
[1] npm WARN cli ^16.13.0 || >=18.0.0`. You can find the latest version at https://nodejs.org/.
npm WARN config cache-min This option has been deprecated in favor of `--prefer-offline`.
[1] npm WARN config cache-max This option has been deprecated in favor of `--prefer-online`
[1] npm WARN config tmp This setting is no longer used.  npm stores temporary files in a special
[1] npm WARN config location in the cache, and they are managed by
[1] npm WARN config     [`cacache`](http://npm.im/cacache).
[1] npm WARN config shrinkwrap Use the --package-lock setting instead.
[1] npm WARN config optional Use `--omit=optional` to exclude optional dependencies, or
[1] npm WARN config `--include=optional` to include them.
npm WARN config 
[1] npm WARN config     Default value does install optional deps unless otherwise omitted.
[2] npm WARN cli npm v9.3.0 does not support Node.js v14.15.0. You should probably upgrade to a
[2] npm WARN cli newer version of node as we can't make any promises that npm will work with this
[2] npm WARN cli version. This version of npm supports the following node versions: `^14.17.0 ||
[2] npm WARN cli ^16.13.0 || >=18.0.0`. You can find the latest version at https://nodejs.org/.
[2] npm WARN config cache-min This option has been deprecated in favor of `--prefer-offline`.
[2] npm WARN config cache-max This option has been deprecated in favor of `--prefer-online`
npm WARN config tmp This setting is no longer used.  npm stores temporary files in a special
[2] npm WARN config location in the cache, and they are managed by
[2] npm WARN config     [`cacache`](http://npm.im/cacache).
[2] npm WARN config shrinkwrap Use the --package-lock setting instead.
[2] npm WARN config optional Use `--omit=optional` to exclude optional dependencies, or
[2] npm WARN config `--include=optional` to include them.
[2] npm WARN config 
[2] npm WARN config     Default value does install optional deps unless otherwise omitted.
[1] 
[1] > @deep-foundation/deeplinks@0.0.101 dev
[1] > (cd local && docker-compose down || true) && cross-env npm_config_yes=true JWT_SECRET="{\"type\":\"HS256\",\"key\":\"3EK6FD+o0+c7tzBNVfjpMkNDi2yARAAKzQlk8O2IKoxQu4nF7EdAh8s3TwpHwrdWT6R\"}" MIGRATIONS_HASURA_PATH=localhost:8080 MIGRATIONS_HASURA_SSL=0 MIGRATIONS_HASURA_SECRET=myadminsecretkey MIGRATIONS_DEEPLINKS_URL=http://host.docker.internal:3006 DEEPLINKS_HASURA_PATH=localhost:8080 DEEPLINKS_HASURA_SSL=0 DEEPLINKS_HASURA_SECRET=myadminsecretkey PORT=3006 npm run launch
[1] 
[2] 
[2] > @deep-foundation/deeplinks@0.0.101 start-engine-docker
[2] > cross-env JWT_SECRET="{\"type\":\"HS256\",\"key\":\"3EK6FD+o0+c7tzBNVfjpMkNDi2yARAAKzQlk8O2IKoxQu4nF7EdAh8s3TwpHwrdWT6R\"}" npm run start-engine-docker-core
[2] 
[1] Network deep-network  Removing
[1] Network deep-network  Error
[1] failed to remove network deep-network: Error response from daemon: error while removing network: network deep-network id b654439d35cd6228c8696ed8dab00eae5cf207cb7dab24669f47e28bba61ddd2 has active endpoints
[3] ready - started server on 0.0.0.0:4000, url: http://localhost:4000
[0] ready - started server on 0.0.0.0:3007, url: http://localhost:3007
[3] warn  - Invalid next.config.js options detected: 
[3]   - The root value has an unexpected property, strictMode, which is not in the list of allowed properties (amp, analyticsId, assetPrefix, basePath, cleanDistDir, compiler, compress, crossOrigin, devIndicators, distDir, env, eslint, excludeDefaultMomentLocales, experimental, exportPathMap, generateBuildId, generateEtags, headers, httpAgentOptions, i18n, images, modularizeImports, onDemandEntries, optimizeFonts, output, outputFileTracing, pageExtensions, poweredByHeader, productionBrowserSourceMaps, publicRuntimeConfig, reactStrictMode, redirects, rewrites, sassOptions, serverRuntimeConfig, skipMiddlewareUrlNormalize, skipTrailingSlashRedirect, staticPageGenerationTimeout, swcMinify, trailingSlash, transpilePackages, typescript, useFileSystemPublicRoutes, webpack).
[3] 
[3] See more info here: https://nextjs.org/docs/messages/invalid-next-config
[0] warn  - Invalid next.config.js options detected: 
[0]   - The root value has an unexpected property, webpack5, which is not in the list of allowed properties (amp, analyticsId, assetPrefix, basePath, cleanDistDir, compiler, compress, crossOrigin, devIndicators, distDir, env, eslint, excludeDefaultMomentLocales, experimental, exportPathMap, generateBuildId, generateEtags, headers, httpAgentOptions, i18n, images, modularizeImports, onDemandEntries, optimizeFonts, output, outputFileTracing, pageExtensions, poweredByHeader, productionBrowserSourceMaps, publicRuntimeConfig, reactStrictMode, redirects, rewrites, sassOptions, serverRuntimeConfig, skipMiddlewareUrlNormalize, skipTrailingSlashRedirect, staticPageGenerationTimeout, swcMinify, trailingSlash, transpilePackages, typescript, useFileSystemPublicRoutes, webpack).
[0]   - The root value has an unexpected property, future, which is not in the list of allowed properties (amp, analyticsId, assetPrefix, basePath, cleanDistDir, compiler, compress, crossOrigin, devIndicators, distDir, env, eslint, excludeDefaultMomentLocales, experimental, exportPathMap, generateBuildId, generateEtags, headers, httpAgentOptions, i18n, images, modularizeImports, onDemandEntries, optimizeFonts, output, outputFileTracing, pageExtensions, poweredByHeader, productionBrowserSourceMaps, publicRuntimeConfig, reactStrictMode, redirects, rewrites, sassOptions, serverRuntimeConfig, skipMiddlewareUrlNormalize, skipTrailingSlashRedirect, staticPageGenerationTimeout, swcMinify, trailingSlash, transpilePackages, typescript, useFileSystemPublicRoutes, webpack).
[0]   - The root value has an unexpected property, strictMode, which is not in the list of allowed properties (amp, analyticsId, assetPrefix, basePath, cleanDistDir, compiler, compress, crossOrigin, devIndicators, distDir, env, eslint, excludeDefaultMomentLocales, experimental, exportPathMap, generateBuildId, generateEtags, headers, httpAgentOptions, i18n, images, modularizeImports, onDemandEntries, optimizeFonts, output, outputFileTracing, pageExtensions, poweredByHeader, productionBrowserSourceMaps, publicRuntimeConfig, reactStrictMode, redirects, rewrites, sassOptions, serverRuntimeConfig, skipMiddlewareUrlNormalize, skipTrailingSlashRedirect, staticPageGenerationTimeout, swcMinify, trailingSlash, transpilePackages, typescript, useFileSystemPublicRoutes, webpack).
[0] 
[0] See more info here: https://nextjs.org/docs/messages/invalid-next-config
[2] npm WARN cli npm v9.3.0 does not support Node.js v14.15.0. You should probably upgrade to a
npm WARN cli newer version of node as we can't make any promises that npm will work with this
[2] npm WARN cli version. This version of npm supports the following node versions: `^14.17.0 ||
[2] npm WARN cli ^16.13.0 || >=18.0.0`. You can find the latest version at https://nodejs.org/.
[2] npm WARN config cache-min This option has been deprecated in favor of `--prefer-offline`.
[2] npm WARN config cache-max This option has been deprecated in favor of `--prefer-online`
[2] npm WARN config tmp This setting is no longer used.  npm stores temporary files in a special
npm WARN config location in the cache, and they are managed by
[2] npm WARN config     [`cacache`](http://npm.im/cacache).
[2] npm WARN config shrinkwrap Use the --package-lock setting instead.
[2] npm WARN config optional Use `--omit=optional` to exclude optional dependencies, or
[2] npm WARN config `--include=optional` to include them.
[2] npm WARN config 
[2] npm WARN config     Default value does install optional deps unless otherwise omitted.
[1] npm WARN cli npm v9.3.0 does not support Node.js v14.15.0. You should probably upgrade to a
[1] npm WARN cli newer version of node as we can't make any promises that npm will work with this
[1] npm WARN cli version. This version of npm supports the following node versions: `^14.17.0 ||
[1] npm WARN cli ^16.13.0 || >=18.0.0`. You can find the latest version at https://nodejs.org/.
[1] npm WARN config cache-min This option has been deprecated in favor of `--prefer-offline`.
[1] npm WARN config cache-max This option has been deprecated in favor of `--prefer-online`
[1] npm WARN config tmp This setting is no longer used.  npm stores temporary files in a special
[1] npm WARN config location in the cache, and they are managed by
[1] npm WARN config     [`cacache`](http://npm.im/cacache).
[1] npm WARN config shrinkwrap Use the --package-lock setting instead.
[1] npm WARN config optional Use `--omit=optional` to exclude optional dependencies, or
[1] npm WARN config `--include=optional` to include them.
[1] npm WARN config 
[1] npm WARN config     Default value does install optional deps unless otherwise omitted.
[1] 
[1] > @deep-foundation/deeplinks@0.0.101 launch
[1] > ts-node ./index.ts;
[1] 
[2] 
[2] > @deep-foundation/deeplinks@0.0.101 start-engine-docker-core
[2] > cd ./node_modules/@deep-foundation/hasura/local && docker-compose --project-name deep up -d
[2] 
[2] time="2023-01-13T19:24:03Z" level=warning msg="volume \"deep-db-data\" already exists but was not created by Docker Compose. Use `external: true` to use an existing volume"
[2] Container deep-postgres  Running
[2] Container deep-hasura  Running
[2] Container deep-minio  Running
[2] Container deep-hasura-storage  Running
[2] npm run gitpod-engine exited with code 0
[3] warn  - The `app` directory is experimental. To enable, add `appDir: true` to your `next.config.js` configuration under `experimental`. See https://nextjs.org/docs/messages/experimental-app-dir-config
[0] warn  - The `app` directory is experimental. To enable, add `appDir: true` to your `next.config.js` configuration under `experimental`. See https://nextjs.org/docs/messages/experimental-app-dir-config
[3] event - compiled client and server successfully in 2.2s (151 modules)
[0] event - compiled client and server successfully in 6.4s (174 modules)
[1] Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /workspace/dev/packages/deeplinks/node_modules/get-port/index.js
[1] require() of ES modules is not supported.
[1] require() of /workspace/dev/packages/deeplinks/node_modules/get-port/index.js from /workspace/dev/packages/deeplinks/imports/container-controller.ts is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
[1] Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /workspace/dev/packages/deeplinks/node_modules/get-port/package.json.
[1] 
[1]     at Module._extensions..js (internal/modules/cjs/loader.js:1080:13)
[1]     at Object.require.extensions.<computed> [as .js] (/workspace/dev/packages/deeplinks/node_modules/ts-node/src/index.ts:1608:43)
[1]     at Module.load (internal/modules/cjs/loader.js:928:32)
[1]     at Function.Module._load (internal/modules/cjs/loader.js:769:14)
[1]     at Module.require (internal/modules/cjs/loader.js:952:19)
[1]     at require (internal/modules/cjs/helpers.js:88:18)
[1]     at Object.<anonymous> (/workspace/dev/packages/deeplinks/imports/container-controller.ts:4:1)
[1]     at Module._compile (internal/modules/cjs/loader.js:1063:30)
[1]     at Module.m._compile (/workspace/dev/packages/deeplinks/node_modules/ts-node/src/index.ts:1618:23)
[1]     at Module._extensions..js (internal/modules/cjs/loader.js:1092:10) {
[1]   code: 'ERR_REQUIRE_ESM'
[1] }
[1] npm run deeplinks exited with code 1
```

**Comment by FreePhoenix888** [comment]
`webhook: 'https://3006-deepfoundation-dev-htv9uitbiie.ws-eu82.gitpod.io///api/reserved-cleaner'`
Three slashes? `///`
