### ISSUE TITLE
Put dev package to package which is not a parent folder for submodules

### ISSUE THREAD

**Issue by FreePhoenix888** [deep-foundation/dev#111]
# Problem
dev package is parent for submodules and therefore its node_modules are shared for all of them and we can build a submodule thinking it is working as intented but without parent node_modules it will not build - for example in github modules.
Imlicitly installed packages from parent node_modules are misleading

# How to fix it
Put dev to a dev folder which will not be a parent folder for submodules

# Note
Scripts are written for the current state of the dev repository and we should change code related to the paths in dev scripts.

**Comment by Konard** [comment]
We need to find a way to make sure that `node_modules` inside `packages` folder are isolated from `dev/node_modules`.

For example we sometimes can do something like this, to get 100% isolation:

```
gitpod /workspace/dev (main) $ cp -r ./npm-packager ../npm-packager
gitpod /workspace/dev (main) $ code ../npm-packager/
```

Or may be even better is to use separate repositories with separate GitPod in them, like here: https://github.com/deep-foundation/npm-packager

**Comment by FreePhoenix888** [comment]
> ```
> gitpod /workspace/dev (main) $ cp -r ./npm-packager ../npm-packager
> gitpod /workspace/dev (main) $ code ../npm-packager/
> ```
@Konard , you will not be able to see the folder if you put it in workspace folder. Workaround is to use `code /workspace/` but I think it is easier to put dev in its own folder to isolate its node_modules

**Comment by FreePhoenix888** [comment]
One more example why we have problems caused by parent node_modules

I have `@deep-foundation/store` installed in `sdk` but  it uses store from dev monorepository node_modules:
```
error - Error: Cannot find module 'next/router'
Require stack:
- /home/freephoenix888/Programming/dev/node_modules/@deep-foundation/store/query.js
- /home/freephoenix888/Programming/dev/packages/sdk/app/server/pages/test.js
- /home/freephoenix888/Programming/dev/packages/sdk/node_modules/next/dist/server/require.js
- /home/freephoenix888/Programming/dev/packages/sdk/node_modules/next/dist/server/next-server.js
- /home/freephoenix888/Programming/dev/packages/sdk/node_modules/next/dist/server/dev/next-dev-server.js
- /home/freephoenix888/Programming/dev/packages/sdk/node_modules/next/dist/server/next.js
- /home/freephoenix888/Programming/dev/packages/sdk/node_modules/next/dist/server/lib/render-server.js
- /home/freephoenix888/Programming/dev/packages/sdk/node_modules/next/dist/compiled/jest-worker/processChild.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1047:15)
    at mod._resolveFilename (/home/freephoenix888/Programming/dev/packages/sdk/node_modules/next/dist/build/webpack/require-hook.js:23:32)
    at Module._load (node:internal/modules/cjs/loader:893:27)
    at Module.require (node:internal/modules/cjs/loader:1113:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/home/freephoenix888/Programming/dev/node_modules/@deep-foundation/store/query.js:26:18)
    at Module._compile (node:internal/modules/cjs/loader:1226:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1280:10)
    at Module.load (node:internal/modules/cjs/loader:1089:32)
    at Module._load (node:internal/modules/cjs/loader:930:12)
    at Module.require (node:internal/modules/cjs/loader:1113:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at @deep-foundation/store/query (/home/freephoenix888/Programming/dev/packages/sdk/app/server/pages/test.js:3618:18)
    at __webpack_require__ (/home/freephoenix888/Programming/dev/packages/sdk/app/server/webpack-runtime.js:33:43)
    at eval (webpack-internal:///./imports/provider.tsx:18:86)
    at ./imports/provider.tsx (/home/freephoenix888/Programming/dev/packages/sdk/app/server/pages/test.js:3574:1)
    at __webpack_require__ (/home/freephoenix888/Programming/dev/packages/sdk/app/server/webpack-runtime.js:33:43)
    at eval (webpack-internal:///./pages/test.tsx:12:75)
    at __webpack_require__.a (/home/freephoenix888/Programming/dev/packages/sdk/app/server/webpack-runtime.js:100:13)
    at eval (webpack-internal:///./pages/test.tsx:1:21)
    at ./pages/test.tsx (/home/freephoenix888/Programming/dev/packages/sdk/app/server/pages/test.js:3585:1)
    at __webpack_require__ (/home/freephoenix888/Programming/dev/packages/sdk/app/server/webpack-runtime.js:33:43)
    at __webpack_exec__ (/home/freephoenix888/Programming/dev/packages/sdk/app/server/pages/test.js:3990:39)
    at /home/freephoenix888/Programming/dev/packages/sdk/app/server/pages/test.js:3991:28
    at Object.<anonymous> (/home/freephoenix888/Programming/dev/packages/sdk/app/server/pages/test.js:3994:3)
    at Module._compile (node:internal/modules/cjs/loader:1226:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1280:10)
    at Module.load (node:internal/modules/cjs/loader:1089:32)
    at Module._load (node:internal/modules/cjs/loader:930:12)
    at Module.require (node:internal/modules/cjs/loader:1113:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.requirePage (/home/freephoenix888/Programming/dev/packages/sdk/node_modules/next/dist/server/require.js:134:12)
    at /home/freephoenix888/Programming/dev/packages/sdk/node_modules/next/dist/server/load-components.js:51:73
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.loadComponentsImpl [as loadComponents] (/home/freephoenix888/Programming/dev/packages/sdk/node_modules/next/dist/server/load-components.js:51:26)
    at async DevServer.findPageComponentsImpl (/home/freephoenix888/Programming/dev/packages/sdk/node_modules/next/dist/server/next-server.js:667:36)
    at async DevServer.findPageComponents (/home/freephoenix888/Programming/dev/packages/sdk/node_modules/next/dist/server/dev/next-dev-server.js:1248:20)
    at async DevServer.renderPageComponent (/home/freephoenix888/Programming/dev/packages/sdk/node_modules/next/dist/server/base-server.js:1187:24)
    at async DevServer.renderToResponseImpl (/home/freephoenix888/Programming/dev/packages/sdk/node_modules/next/dist/server/base-server.js:1230:32)
    at async DevServer.pipeImpl (/home/freephoenix888/Programming/dev/packages/sdk/node_modules/next/dist/server/base-server.js:548:25)
    at async Object.fn (/home/freephoenix888/Programming/dev/packages/sdk/node_modules/next/dist/server/next-server.js:1030:21)
    at async Router.execute (/home/freephoenix888/Programming/dev/packages/sdk/node_modules/next/dist/server/router.js:297:32)
    at async DevServer.runImpl (/home/freephoenix888/Programming/dev/packages/sdk/node_modules/next/dist/server/base-server.js:522:29)
    at async DevServer.run (/home/freephoenix888/Programming/dev/packages/sdk/node_modules/next/dist/server/dev/next-dev-server.js:869:20)
    at async DevServer.handleRequestImpl (/home/freephoenix888/Programming/dev/packages/sdk/node_modules/next/dist/server/base-server.js:456:20) {
  digest: undefined
}
^Cwarn  - The `app` directory is experimental. To enable, add `appDir: true` to your `next.config.js` configuration under `experimental`. See https://nextjs.org/docs/messages/experimental-app-dir-config


freephoenix888@freephoenix888:~/Programming/dev/packages/sdk$ npm list @deep-foundation/store
@deep-foundation/sdk@0.0.0 /home/freephoenix888/Programming/dev/packages/sdk
└─┬ @deep-foundation/deeplinks@0.0.142 extraneous -> ./../deeplinks
  ├─┬ @deep-foundation/deeplinks@0.0.141 invalid: "file:deep-foundation-deeplinks-0.0.141.tgz" from ../deeplinks extraneous
  │ └── @deep-foundation/store@0.0.18 deduped
  └── @deep-foundation/store@0.0.18 extraneous

```
