### ISSUE TITLE
`ERESOLVE unable to resolve dependency tree` while running `npm run packages`

### ISSUE THREAD

**Issue by kalinochkind** [deep-foundation/dev#164]
### Describe the bug

I am trying to install deep locally and following the instruction from README, however, the `npm run packages` step fails

### Expected Behavior

Successful initialization of submodules

### Current Behavior

Error
```
[0] packages/npm-packager npm ci
[0] npm ERR! code ERESOLVE
[0] npm ERR! ERESOLVE unable to resolve dependency tree
[0] npm ERR! 
[0] npm ERR! While resolving: @deep-foundation/npm-packager@0.0.38
npm ERR! Found: @deep-foundation/deeplinks@0.0.295
[0] npm ERR! node_modules/@deep-foundation/deeplinks
[0] npm ERR!   @deep-foundation/deeplinks@"^0.0.295" from the root project
[0] npm ERR! 
[0] npm ERR! Could not resolve dependency:
npm ERR! peer @deep-foundation/deeplinks@"~0.0.298" from @deep-foundation/npm-automation@18.1.10
[0] npm ERR! node_modules/@deep-foundation/npm-automation
[0] npm ERR!   dev @deep-foundation/npm-automation@"^18.1.10" from the root project
[0] npm ERR! 
[0] npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
[0] npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
[0] npm ERR! 
[0] npm ERR! See /home/denis/.npm/eresolve-report.txt for a full report.
[0] 
[0] npm ERR! A complete log of this run can be found in:
[0] npm ERR!     /home/denis/.npm/_logs/2023-09-25T17_50_07_161Z-debug.log
[0] echo "packages/hasura npm ci" && cd /home/denis/dev/packages/hasura && npm ci && cd ../.. && echo "packages/deeplinks npm ci" && cd /home/denis/dev/packages/deeplinks && npm ci && cd ../.. && echo "packages/deepcase npm ci" && cd /home/denis/dev/packages/deepcase && npm ci && cd ../.. && echo "packages/deepcase-app npm ci" && cd /home/denis/dev/packages/deepcase-app && npm ci && cd ../.. && echo "packages/sdk npm ci" && cd /home/denis/dev/packages/sdk && npm ci && cd ../.. && echo "packages/gh-pages npm ci" && cd /home/denis/dev/packages/gh-pages && npm ci && cd ../.. && echo "packages/materialized-path npm ci" && cd /home/denis/dev/packages/materialized-path && npm ci && cd ../.. && echo "packages/store npm ci" && cd /home/denis/dev/packages/store && npm ci && cd ../.. && echo "packages/react-hasura npm ci" && cd /home/denis/dev/packages/react-hasura && npm ci && cd ../.. && echo "packages/js-docker-isolation-provider npm ci" && cd /home/denis/dev/packages/js-docker-isolation-provider && npm ci && cd ../.. && echo "packages/python-docker-isolation-provider npm ci" && cd /home/denis/dev/packages/python-docker-isolation-provider && npm ci && cd ../.. && echo "packages/workflows npm ci" && cd /home/denis/dev/packages/workflows && npm ci && cd ../.. && echo "packages/npm-packager npm ci" && cd /home/denis/dev/packages/npm-packager && npm ci && cd ../.. && echo "packages/deep-memo-app npm ci" && cd /home/denis/dev/packages/deep-memo-app && npm ci && cd ../.. && echo "packages/deep-memo npm ci" && cd /home/denis/dev/packages/deep-memo && npm ci exited with code 1
[21:50:07] 'packages:ci' errored after 5.52 min
[21:50:07] Error: [object Object]
    at formatError (/home/denis/dev/node_modules/gulp-cli/lib/versioned/^4.0.0/format-error.js:21:10)
    at Gulp.<anonymous> (/home/denis/dev/node_modules/gulp-cli/lib/versioned/^4.0.0/log/events.js:33:15)
    at Gulp.emit (node:events:529:35)
    at Gulp.emit (node:domain:489:12)
    at Object.error (/home/denis/dev/node_modules/undertaker/lib/helpers/createExtensions.js:61:10)
    at handler (/home/denis/dev/node_modules/now-and-later/lib/map.js:50:14)
    at f (/home/denis/dev/node_modules/once/once.js:25:25)
    at f (/home/denis/dev/node_modules/once/once.js:25:25)
    at tryCatch (/home/denis/dev/node_modules/async-done/index.js:24:15)
    at done (/home/denis/dev/node_modules/async-done/index.js:40:12)
```

### Steps to reproduce

Check out commit 495b0556d4180504a6c980ba5bebb0d001630d4d of this repo (`npm-packager` submodule commit: 7f45ce339677274d589b58ab91893e66fcd3a8fb)
Run `npm ci`
Run `npm run packages`

### Environment

```shell
## System:
 - OS: Linux 6.2 Ubuntu 22.04.3 LTS 22.04.3 LTS (Jammy Jellyfish)
 - CPU: (4) x64 Intel(R) Core(TM) i7-10610U CPU @ 1.80GHz
 - Memory: 5.56 GB / 7.75 GB
 - Container: Yes
 - Shell: 5.1.16 - /bin/bash
## npmPackages:
 - @deep-foundation/hasura: ^0.0.51 => 0.0.51 
 - @types/gulp: ^4.0.8 => 4.0.14 
 - commander: ^11.0.0 => 11.0.0 
 - concurrently: ^5.3.0 => 5.3.0 
 - cross-env: ^7.0.3 => 7.0.3 
 - del: ^6.0.0 => 6.1.1 
 - dequal: ^2.0.3 => 2.0.3 
 - gulp: ^4.0.2 => 4.0.2 
 - gulp-run-command: ^0.0.10 => 0.0.10 
 - i: ^0.3.6 => 0.3.7 
 - minimist: ^1.2.5 => 1.2.8 
 - npm: ^7.5.4 => 7.24.2 
 - prompt: ^1.2.0 => 1.3.0 
 - rimraf: ^3.0.2 => 3.0.2 
 - simple-git: ^2.45.0 => 2.48.0 
 - subscriptions-transport-ws: ^0.11.0 => 0.11.0 
 - ts-node: ^10.9.1 => 10.9.1 
 - typescript: ^4.9.5 => 4.9.5
```

**Comment by kalinochkind** [comment]
Fixed by https://github.com/deep-foundation/npm-packager/commit/a9dbe93fd049b1019fa05211e5078f82c20de9ce
