### ISSUE TITLE
Type 30 not founded.

### ISSUE THREAD

**Issue by TimaxLacs** [deep-foundation/dev#209]
### Bug description

An error occurred when trying to add a text file link to the deepcase

### Current Behavior

```
                    throw new Error(`DeepClient Insert Error: ${e.message}`, { cause: e });
                          ^

Error: DeepClient Insert Error: Type 30 not founded.
    at DeepClient.<anonymous> (file:///C:/Users/samsung/Deep.project/sync-file/deep-files-sync/node_modules/@deep-foundation/deeplinks/imports/client.js:466:27)
    at Generator.throw (<anonymous>)
    at rejected (file:///C:/Users/samsung/Deep.project/sync-file/deep-files-sync/node_modules/@deep-foundation/deeplinks/imports/client.js:5:65)   
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  [cause]: ApolloError: Type 30 not founded.
      at new ApolloError (C:\Users\samsung\Deep.project\sync-file\deep-files-sync\node_modules\@apollo\client\errors\errors.cjs:33:28)
      at C:\Users\samsung\Deep.project\sync-file\deep-files-sync\node_modules\@apollo\client\core\core.cjs:1427:47
      at both (C:\Users\samsung\Deep.project\sync-file\deep-files-sync\node_modules\@apollo\client\utilities\utilities.cjs:1269:31)
      at C:\Users\samsung\Deep.project\sync-file\deep-files-sync\node_modules\@apollo\client\utilities\utilities.cjs:1260:72
      at new Promise (<anonymous>)
      at Object.then (C:\Users\samsung\Deep.project\sync-file\deep-files-sync\node_modules\@apollo\client\utilities\utilities.cjs:1260:24)
      at Object.next (C:\Users\samsung\Deep.project\sync-file\deep-files-sync\node_modules\@apollo\client\utilities\utilities.cjs:1271:49)
      at notifySubscription (C:\Users\samsung\Deep.project\sync-file\deep-files-sync\node_modules\zen-observable\lib\Observable.js:135:18)
      at onNotify (C:\Users\samsung\Deep.project\sync-file\deep-files-sync\node_modules\zen-observable\lib\Observable.js:179:3)
      at SubscriptionObserver.next (C:\Users\samsung\Deep.project\sync-file\deep-files-sync\node_modules\zen-observable\lib\Observable.js:235:7) { 
    graphQLErrors: [
      {
        extensions: {
          internal: {
            statement: `WITH "links__mutation_result_alias" AS (INSERT INTO "public"."links" ( "from_id", "type_id", "id", "to_id" ) VALUES (DEFAULT, ('30')::bigint, DEFAULT, DEFAULT)  RETURNING * , ('true')::boolean AS "check__constraint"), "links__all_columns_alias" AS (SELECT  "id" , "from_id" , "to_id" , "type_id"  FROM "links__mutation_result_alias"      ) SELECT  json_build_object('returning', (SELECT  coalesce(json_agg("root" ), '[]' ) AS "root" FROM  (SELECT  row_to_json((SELECT  "_1_e"  FROM  (SELECT  "_0_root.base"."id" AS "id", 'links' AS "__typename"       ) AS "_1_e"  
    ) ) AS "root" FROM  (SELECT  *  FROM "links__all_columns_alias" WHERE ('true')     ) AS "_0_root.base"      ) AS "_2_root"      ), '__typename', 'links_mutation_response' ) , (SELECT  coalesce(bool_and("check__constraint" ), 'true' )  FROM "links__mutation_result_alias"      )        `,   
            prepared: false,
            error: [Object],
            arguments: []
          },
          path: '$.selectionSet.insert_links.args.objects',
          code: 'unexpected'
        },
        message: 'database query error'
      }
    ],
    protocolErrors: [],
    clientErrors: [],
    networkError: null,
    extraInfo: undefined
  }
}
```

### Steps to reproduce

 использования deep.insert c "deep.id('@deep-foundation/core', 'SyncTextFile')"

**Comment by Konard** [comment]
To fix this bug, we have to find a stable way to reproduce it.
