### ISSUE TITLE
Failed to proxy http://localhost:3006/gql Error: socket hang up after stopping js docker provider

### ISSUE THREAD

**Issue by FreePhoenix888** [deep-foundation/dev#224]
# Error
In deepcase I have such error
```
Uncaught (in promise) Error: DeepClient Select Error: Response not successful: Received status code 500
    at DeepClient.eval (client.js:394:1)
    at Generator.throw (<anonymous>)
    at rejected (client.js:5:42)
```
500 http code is internal error therefore I have checked deep terminal and here are the errors :
```
[0] Failed to proxy http://localhost:3006/gql Error: socket hang up
[0]     at connResetException (node:internal/errors:720:14)
[0]     at Socket.socketCloseListener (node:_http_client:474:25)
[0]     at Socket.emit (node:events:526:35)
[0]     at TCP.<anonymous> (node:net:323:12)
[0]     at TCP.callbackTrampoline (node:internal/async_hooks:130:17) {
[0]   code: 'ECONNRESET'
[0] }
[0] Error: socket hang up
[0]     at connResetException (node:internal/errors:720:14)
[0]     at Socket.socketCloseListener (node:_http_client:474:25)
[0]     at Socket.emit (node:events:526:35)
[0]     at TCP.<anonymous> (node:net:323:12)
[0]     at TCP.callbackTrampoline (node:internal/async_hooks:130:17) {
[0]   code: 'ECONNRESET'
[0] }
[0] Failed to proxy http://localhost:3006/gql Error: socket hang up
[0]     at connResetException (node:internal/errors:720:14)
[0]     at Socket.socketCloseListener (node:_http_client:474:25)
[0]     at Socket.emit (node:events:526:35)
[0]     at TCP.<anonymous> (node:net:323:12)
[0]     at TCP.callbackTrampoline (node:internal/async_hooks:130:17) {
[0]   code: 'ECONNRESET'
[0] }
[0] Error: socket hang up
[0]     at connResetException (node:internal/errors:720:14)
[0]     at Socket.socketCloseListener (node:_http_client:474:25)
[0]     at Socket.emit (node:events:526:35)
[0]     at TCP.<anonymous> (node:net:323:12)
[0]     at TCP.callbackTrampoline (node:internal/async_hooks:130:17) {
[0]   code: 'ECONNRESET'
[0] }
[0] Failed to proxy http://localhost:3006/gql Error: socket hang up
[0]     at connResetException (node:internal/errors:720:14)
[0]     at Socket.socketCloseListener (node:_http_client:474:25)
[0]     at Socket.emit (node:events:526:35)
[0]     at TCP.<anonymous> (node:net:323:12)
[0]     at TCP.callbackTrampoline (node:internal/async_hooks:130:17) {
[0]   code: 'ECONNRESET'
[0] }
[0] Error: socket hang up
[0]     at connResetException (node:internal/errors:720:14)
[0]     at Socket.socketCloseListener (node:_http_client:474:25)
[0]     at Socket.emit (node:events:526:35)
[0]     at TCP.<anonymous> (node:net:323:12)
[0]     at TCP.callbackTrampoline (node:internal/async_hooks:130:17) {
[0]   code: 'ECONNRESET'
[0] }
[0] Failed to proxy http://localhost:3006/gql Error: socket hang up
[0]     at connResetException (node:internal/errors:720:14)
[0]     at Socket.socketCloseListener (node:_http_client:474:25)
[0]     at Socket.emit (node:events:526:35)
[0]     at TCP.<anonymous> (node:net:323:12)
[0]     at TCP.callbackTrampoline (node:internal/async_hooks:130:17) {
[0]   code: 'ECONNRESET'
[0] }
[0] Error: socket hang up
[0]     at connResetException (node:internal/errors:720:14)
[0]     at Socket.socketCloseListener (node:_http_client:474:25)
[0]     at Socket.emit (node:events:526:35)
[0]     at TCP.<anonymous> (node:net:323:12)
[0]     at TCP.callbackTrampoline (node:internal/async_hooks:130:17) {
[0]   code: 'ECONNRESET'
[0] }
[0] Failed to proxy http://localhost:3006/gql Error: socket hang up
[0]     at connResetException (node:internal/errors:720:14)
[0]     at Socket.socketCloseListener (node:_http_client:474:25)
[0]     at Socket.emit (node:events:526:35)
[0]     at TCP.<anonymous> (node:net:323:12)
[0]     at TCP.callbackTrampoline (node:internal/async_hooks:130:17) {
[0]   code: 'ECONNRESET'
[0] }
[0] Error: socket hang up
[0]     at connResetException (node:internal/errors:720:14)
[0]     at Socket.socketCloseListener (node:_http_client:474:25)
[0]     at Socket.emit (node:events:526:35)
[0]     at TCP.<anonymous> (node:net:323:12)
[0]     at TCP.callbackTrampoline (node:internal/async_hooks:130:17) {
[0]   code: 'ECONNRESET'
[0] }
[0] Failed to proxy http://localhost:3006/gql Error: socket hang up
[0]     at connResetException (node:internal/errors:720:14)
[0]     at Socket.socketCloseListener (node:_http_client:474:25)
[0]     at Socket.emit (node:events:526:35)
[0]     at TCP.<anonymous> (node:net:323:12)
[0]     at TCP.callbackTrampoline (node:internal/async_hooks:130:17) {
[0]   code: 'ECONNRESET'
[0] }
[0] Error: socket hang up
[0]     at connResetException (node:internal/errors:720:14)
[0]     at Socket.socketCloseListener (node:_http_client:474:25)
[0]     at Socket.emit (node:events:526:35)
[0]     at TCP.<anonymous> (node:net:323:12)
[0]     at TCP.callbackTrampoline (node:internal/async_hooks:130:17) {
[0]   code: 'ECONNRESET'
[0] }
[0] Failed to proxy http://localhost:3006/gql Error: socket hang up
[0]     at connResetException (node:internal/errors:720:14)
[0]     at Socket.socketCloseListener (node:_http_client:474:25)
[0]     at Socket.emit (node:events:526:35)
[0]     at TCP.<anonymous> (node:net:323:12)
[0]     at TCP.callbackTrampoline (node:internal/async_hooks:130:17) {
[0]   code: 'ECONNRESET'
[0] }
[0] Error: socket hang up
[0]     at connResetException (node:internal/errors:720:14)
[0]     at Socket.socketCloseListener (node:_http_client:474:25)
[0]     at Socket.emit (node:events:526:35)
[0]     at TCP.<anonymous> (node:net:323:12)
[0]     at TCP.callbackTrampoline (node:internal/async_hooks:130:17) {
[0]   code: 'ECONNRESET'
[0] }
```

# Description
I could not install a package and stopped js docker provider and then restarted deep. Now I have this problem

**Comment by Konard** [comment]
@FreePhoenix888 is it still reproducible?

**Comment by FreePhoenix888** [comment]
> @FreePhoenix888 is it still reproducible?

no
