### ISSUE TITLE
sdk npm ci does not work on the first time

### ISSUE THREAD

**Issue by Konard** [deep-foundation/dev#229]
Error in GitPod Task 1:
```
[0] packages/sdk npm ci
[0] npm WARN deprecated source-map-url@0.4.1: See https://github.com/lydell/source-map-url#deprecated
[0] npm WARN deprecated rtrim@1.0.1: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
[0] npm WARN deprecated phin@2.9.3: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
[0] npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
[0] npm WARN deprecated abab@2.0.6: Use your platform's native atob() and btoa() methods instead
[0] npm WARN deprecated boom@7.3.0: This module has moved and is now available at @hapi/boom. Please update your dependencies as this version is no longer maintained an may contain bugs and security issues.
[0] npm WARN deprecated apollo-datasource@3.3.2: The `apollo-datasource` package is part of Apollo Server v2 and v3, which are now deprecated (end-of-life October 22nd 2023). See https://www.apollographql.com/docs/apollo-server/previous-versions/ for more details.
[0] npm WARN deprecated apollo-datasource@0.10.0: The `apollo-datasource` package is part of Apollo Server v2 and v3, which are now deprecated (end-of-life October 22nd 2023 and October 22nd 2024, respectively). See https://www.apollographql.com/docs/apollo-server/previous-versions/ for more details.
[0] npm WARN deprecated apollo-datasource@0.10.0: The `apollo-datasource` package is part of Apollo Server v2 and v3, which are now deprecated (end-of-life October 22nd 2023). See https://www.apollographql.com/docs/apollo-server/previous-versions/ for more details.
[0] npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
[0] npm WARN deprecated hoek@6.1.3: This module has moved and is now available at @hapi/hoek. Please update your dependencies as this version is no longer maintained an may contain bugs and security issues.
[0] npm WARN deprecated apollo-tracing@0.16.0: The `apollo-tracing` package is no longer part of Apollo Server 3. See https://www.apollographql.com/docs/apollo-server/migration/#tracing for details
[0] npm WARN deprecated acorn-dynamic-import@2.0.2: This is probably built in to whatever tool you're using. If you still need it... idk
[0] npm WARN deprecated apollo-server-plugin-base@3.7.2: The `apollo-server-plugin-base` package is part of Apollo Server v2 and v3, which are now deprecated (end-of-life October 22nd 2023). This package's functionality is now found in the `@apollo/server` package. See https://www.apollographql.com/docs/apollo-server/previous-versions/ for more details.
[0] npm WARN deprecated source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated
[0] npm WARN deprecated domexception@2.0.1: Use your platform's native DOMException instead
[0] npm WARN deprecated apollo-server-types@3.8.0: The `apollo-server-types` package is part of Apollo Server v2 and v3, which are now deprecated (end-of-life October 22nd 2023). This package's functionality is now found in the `@apollo/server` package. See https://www.apollographql.com/docs/apollo-server/previous-versions/ for more details.
[0] npm WARN deprecated apollo-server-errors@3.3.1: The `apollo-server-errors` package is part of Apollo Server v2 and v3, which are now deprecated (end-of-life October 22nd 2023). This package's functionality is now found in the `@apollo/server` package. See https://www.apollographql.com/docs/apollo-server/previous-versions/ for more details.
[0] npm WARN deprecated accept@3.1.3: This module has moved and is now available at @hapi/accept. Please update your dependencies as this version is no longer maintained an may contain bugs and security issues.
[0] npm WARN deprecated apollo-server-plugin-base@0.14.0: The `apollo-server-plugin-base` package is part of Apollo Server v2 and v3, which are now deprecated (end-of-life October 22nd 2023). This package's functionality is now found in the `@apollo/server` package. See https://www.apollographql.com/docs/apollo-server/previous-versions/ for more details.
[0] npm WARN deprecated apollo-server-plugin-base@0.14.0: The `apollo-server-plugin-base` package is part of Apollo Server v2 and v3, which are now deprecated (end-of-life October 22nd 2023 and October 22nd 2024, respectively). This package's functionality is now found in the `@apollo/server` package. See https://www.apollographql.com/docs/apollo-server/previous-versions/ for more details.
[0] npm WARN deprecated apollo-server-plugin-base@0.14.0: The `apollo-server-plugin-base` package is part of Apollo Server v2 and v3, which are now deprecated (end-of-life October 22nd 2023). This package's functionality is now found in the `@apollo/server` package. See https://www.apollographql.com/docs/apollo-server/previous-versions/ for more details.
[0] npm WARN deprecated apollo-server-plugin-base@0.14.0: The `apollo-server-plugin-base` package is part of Apollo Server v2 and v3, which are now deprecated (end-of-life October 22nd 2023). This package's functionality is now found in the `@apollo/server` package. See https://www.apollographql.com/docs/apollo-server/previous-versions/ for more details.
[0] npm WARN deprecated w3c-hr-time@1.0.2: Use your platform's native performance.now() and performance.timeOrigin.
[0] npm WARN deprecated apollo-server-types@0.10.0: The `apollo-server-types` package is part of Apollo Server v2 and v3, which are now deprecated (end-of-life October 22nd 2023). This package's functionality is now found in the `@apollo/server` package. See https://www.apollographql.com/docs/apollo-server/previous-versions/ for more details.
[0] npm WARN deprecated apollo-server-types@0.10.0: The `apollo-server-types` package is part of Apollo Server v2 and v3, which are now deprecated (end-of-life October 22nd 2023). This package's functionality is now found in the `@apollo/server` package. See https://www.apollographql.com/docs/apollo-server/previous-versions/ for more details.
[0] npm WARN deprecated apollo-server-types@0.10.0: The `apollo-server-types` package is part of Apollo Server v2 and v3, which are now deprecated (end-of-life October 22nd 2023 and October 22nd 2024, respectively). This package's functionality is now found in the `@apollo/server` package. See https://www.apollographql.com/docs/apollo-server/previous-versions/ for more details.
[0] npm WARN deprecated apollo-server-types@0.10.0: The `apollo-server-types` package is part of Apollo Server v2 and v3, which are now deprecated (end-of-life October 22nd 2023). This package's functionality is now found in the `@apollo/server` package. See https://www.apollographql.com/docs/apollo-server/previous-versions/ for more details.
[0] npm WARN deprecated apollo-server-types@0.10.0: The `apollo-server-types` package is part of Apollo Server v2 and v3, which are now deprecated (end-of-life October 22nd 2023). This package's functionality is now found in the `@apollo/server` package. See https://www.apollographql.com/docs/apollo-server/previous-versions/ for more details.
[0] npm WARN deprecated graphql-extensions@0.16.0: The `graphql-extensions` API has been removed from Apollo Server 3. Use the plugin API instead: https://www.apollographql.com/docs/apollo-server/integrations/plugins/
[0] npm WARN deprecated formidable@1.2.6: Please upgrade to latest, formidable@v2 or formidable@v3! Check these notes: https://bit.ly/2ZEqIau
[0] npm WARN deprecated sourcemap-codec@1.4.8: Please use @jridgewell/sourcemap-codec instead
[0] npm WARN deprecated sane@4.1.0: some dependency vulnerabilities fixed, support for node < 10 dropped, and newer ECMAScript syntax/features added
[0] npm WARN deprecated chokidar@2.1.8: Chokidar 2 does not receive security updates since 2019. Upgrade to chokidar 3 with 15x fewer dependencies
[0] npm WARN deprecated apollo-server-errors@2.5.0: The `apollo-server-errors` package is part of Apollo Server v2 and v3, which are now deprecated (end-of-life October 22nd 2023 and October 22nd 2024, respectively). This package's functionality is now found in the `@apollo/server` package. See https://www.apollographql.com/docs/apollo-server/previous-versions/ for more details.
[0] npm WARN deprecated apollo-server-errors@2.5.0: The `apollo-server-errors` package is part of Apollo Server v2 and v3, which are now deprecated (end-of-life October 22nd 2023). This package's functionality is now found in the `@apollo/server` package. See https://www.apollographql.com/docs/apollo-server/previous-versions/ for more details.
[0] npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
[0] npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
[0] npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
[0] npm WARN deprecated apollo-cache-control@0.15.0: The functionality provided by the `apollo-cache-control` package is built in to `apollo-server-core` starting with Apollo Server 3. See https://www.apollographql.com/docs/apollo-server/migration/#cachecontrol for details.
[0] npm WARN deprecated rollup-plugin-terser@7.0.2: This package has been deprecated and is no longer maintained. Please use @rollup/plugin-terser
[0] npm WARN deprecated apollo-server-env@4.2.1: The `apollo-server-env` package is part of Apollo Server v2 and v3, which are now deprecated (end-of-life October 22nd 2023). This package's functionality is now found in the `@apollo/utils.fetcher` package. See https://www.apollographql.com/docs/apollo-server/previous-versions/ for more details.
[0] npm WARN deprecated apollo-server-caching@0.7.0: This package is part of the legacy caching implementation used by Apollo Server v2 and v3, and is no longer maintained. We recommend you switch to the newer Keyv-based implementation (which is compatible with all versions of Apollo Server). See https://www.apollographql.com/docs/apollo-server/v3/performance/cache-backends#legacy-caching-implementation for more details.
[0] npm WARN deprecated apollo-server-micro@2.26.2: The `apollo-server-micro` package is part of Apollo Server v2 and v3, which are now deprecated (end-of-life October 22nd 2023 and October 22nd 2024, respectively). This package's functionality is now found in the `@apollo/server` package. See https://www.apollographql.com/docs/apollo-server/previous-versions/ for more details.
[0] npm WARN deprecated har-validator@5.1.5: this library is no longer supported
[0] npm WARN deprecated apollo-reporting-protobuf@0.8.0: The `apollo-reporting-protobuf` package is part of Apollo Server v2 and v3, which are now deprecated (end-of-life October 22nd 2023). This package's functionality is now found in the `@apollo/usage-reporting-protobuf` package. See https://www.apollographql.com/docs/apollo-server/previous-versions/ for more details.
[0] npm WARN deprecated apollo-reporting-protobuf@0.8.0: The `apollo-reporting-protobuf` package is part of Apollo Server v2 and v3, which are now deprecated (end-of-life October 22nd 2023). This package's functionality is now found in the `@apollo/usage-reporting-protobuf` package. See https://www.apollographql.com/docs/apollo-server/previous-versions/ for more details.
[0] npm WARN deprecated apollo-reporting-protobuf@0.8.0: The `apollo-reporting-protobuf` package is part of Apollo Server v2 and v3, which are now deprecated (end-of-life October 22nd 2023 and October 22nd 2024, respectively). This package's functionality is now found in the `@apollo/usage-reporting-protobuf` package. See https://www.apollographql.com/docs/apollo-server/previous-versions/ for more details.
[0] npm WARN deprecated apollo-reporting-protobuf@0.8.0: The `apollo-reporting-protobuf` package is part of Apollo Server v2 and v3, which are now deprecated (end-of-life October 22nd 2023). This package's functionality is now found in the `@apollo/usage-reporting-protobuf` package. See https://www.apollographql.com/docs/apollo-server/previous-versions/ for more details.
[0] npm WARN deprecated apollo-reporting-protobuf@0.8.0: The `apollo-reporting-protobuf` package is part of Apollo Server v2 and v3, which are now deprecated (end-of-life October 22nd 2023). This package's functionality is now found in the `@apollo/usage-reporting-protobuf` package. See https://www.apollographql.com/docs/apollo-server/previous-versions/ for more details.
[0] npm WARN deprecated apollo-reporting-protobuf@3.4.0: The `apollo-reporting-protobuf` package is part of Apollo Server v2 and v3, which are now deprecated (end-of-life October 22nd 2023). This package's functionality is now found in the `@apollo/usage-reporting-protobuf` package. See https://www.apollographql.com/docs/apollo-server/previous-versions/ for more details.
[0] npm WARN deprecated apollo-server-env@3.2.0: The `apollo-server-env` package is part of Apollo Server v2 and v3, which are now deprecated (end-of-life October 22nd 2023). This package's functionality is now found in the `@apollo/utils.fetcher` package. See https://www.apollographql.com/docs/apollo-server/previous-versions/ for more details.
[0] npm WARN deprecated apollo-server-env@3.2.0: The `apollo-server-env` package is part of Apollo Server v2 and v3, which are now deprecated (end-of-life October 22nd 2023). This package's functionality is now found in the `@apollo/utils.fetcher` package. See https://www.apollographql.com/docs/apollo-server/previous-versions/ for more details.
[0] npm WARN deprecated apollo-server-env@3.2.0: The `apollo-server-env` package is part of Apollo Server v2 and v3, which are now deprecated (end-of-life October 22nd 2023 and October 22nd 2024, respectively). This package's functionality is now found in the `@apollo/utils.fetcher` package. See https://www.apollographql.com/docs/apollo-server/previous-versions/ for more details.
[0] npm WARN deprecated apollo-server-env@3.2.0: The `apollo-server-env` package is part of Apollo Server v2 and v3, which are now deprecated (end-of-life October 22nd 2023). This package's functionality is now found in the `@apollo/utils.fetcher` package. See https://www.apollographql.com/docs/apollo-server/previous-versions/ for more details.
[0] npm WARN deprecated apollo-server-env@3.2.0: The `apollo-server-env` package is part of Apollo Server v2 and v3, which are now deprecated (end-of-life October 22nd 2023). This package's functionality is now found in the `@apollo/utils.fetcher` package. See https://www.apollographql.com/docs/apollo-server/previous-versions/ for more details.
[0] npm WARN deprecated workbox-cacheable-response@6.6.0: workbox-background-sync@6.6.0
[0] npm WARN deprecated apollo-server@2.26.1: The `apollo-server` package is part of Apollo Server v2 and v3, which are now deprecated (end-of-life October 22nd 2023). This package's functionality is now found in the `@apollo/server` package. See https://www.apollographql.com/docs/apollo-server/previous-versions/ for more details.
[0] npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
[0] npm WARN deprecated subscriptions-transport-ws@0.9.19: The `subscriptions-transport-ws` package is no longer maintained. We recommend you use `graphql-ws` instead. For help migrating Apollo software to `graphql-ws`, see https://www.apollographql.com/docs/apollo-server/data/subscriptions/#switching-from-subscriptions-transport-ws    For general help using `graphql-ws`, see https://github.com/enisdenjo/graphql-ws/blob/master/README.md
[0] npm WARN deprecated graphql-tools@4.0.8: This package has been deprecated and now it only exports makeExecutableSchema.\nAnd it will no longer receive updates.\nWe recommend you to migrate to scoped packages such as @graphql-tools/schema, @graphql-tools/utils and etc.\nCheck out https://www.graphql-tools.com to learn what package you should use instead
[0] npm WARN deprecated apollo-server-core@2.26.2: The `apollo-server-core` package is part of Apollo Server v2 and v3, which are now deprecated (end-of-life October 22nd 2023 and October 22nd 2024, respectively). This package's functionality is now found in the `@apollo/server` package. See https://www.apollographql.com/docs/apollo-server/previous-versions/ for more details.
[0] npm WARN deprecated apollo-server-core@2.26.2: The `apollo-server-core` package is part of Apollo Server v2 and v3, which are now deprecated (end-of-life October 22nd 2023 and October 22nd 2024, respectively). This package's functionality is now found in the `@apollo/server` package. See https://www.apollographql.com/docs/apollo-server/previous-versions/ for more details.
[0] npm WARN deprecated xterm@5.3.0: This package is now deprecated. Move to @xterm/xterm instead.
[0] npm WARN deprecated @belivvr/aframe-react@0.4.2: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
[0] npm WARN deprecated apollo-server-express@2.26.2: The `apollo-server-express` package is part of Apollo Server v2 and v3, which are now deprecated (end-of-life October 22nd 2023 and October 22nd 2024, respectively). This package's functionality is now found in the `@apollo/server` package. See https://www.apollographql.com/docs/apollo-server/previous-versions/ for more details.
[0] npm WARN tarball tarball data for three-bmfont-text@git+ssh://git@github.com/dmarcos/three-bmfont-text.git#eed4878795be9b3e38cf6aec6b903f56acd1f695 (sha512-JcaccaRCcK/A4c0igPQ9RCw91cil7pLhogDVmrThEvP20B/vbFaaNlmn3frF7pWeo3lATUiNrxVfgxm9qfr9GA==) seems to be corrupted. Trying again.
[0] npm WARN deprecated core-js@2.6.12: core-js@<3.23.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Some versions have web compatibility issues. Please, upgrade your dependencies to the actual version of core-js.
[0] npm WARN tarball tarball data for three-bmfont-text@git+ssh://git@github.com/dmarcos/three-bmfont-text.git#eed4878795be9b3e38cf6aec6b903f56acd1f695 (sha512-JcaccaRCcK/A4c0igPQ9RCw91cil7pLhogDVmrThEvP20B/vbFaaNlmn3frF7pWeo3lATUiNrxVfgxm9qfr9GA==) seems to be corrupted. Trying again.
[0] npm ERR! code EINTEGRITY
[0] npm ERR! sha512-JcaccaRCcK/A4c0igPQ9RCw91cil7pLhogDVmrThEvP20B/vbFaaNlmn3frF7pWeo3lATUiNrxVfgxm9qfr9GA== integrity checksum failed when using sha512: wanted sha512-JcaccaRCcK/A4c0igPQ9RCw91cil7pLhogDVmrThEvP20B/vbFaaNlmn3frF7pWeo3lATUiNrxVfgxm9qfr9GA== but got sha512-FDlyR8SyHQ0Ek38qBx5Hg/AwPuBI/1w/QWpMgzw19Vn81xsDNFTOXJpU0HcvI78C72wwXjJ3T7+EX7k2geDV4Q==. (7553 bytes)
[0] 
[0] npm ERR! A complete log of this run can be found in:
[0] npm ERR!     /home/gitpod/.npm/_logs/2024-04-17T19_26_12_354Z-debug.log
```

Actual error: 
```
[0] npm ERR! code EINTEGRITY
[0] npm ERR! sha512-JcaccaRCcK/A4c0igPQ9RCw91cil7pLhogDVmrThEvP20B/vbFaaNlmn3frF7pWeo3lATUiNrxVfgxm9qfr9GA== integrity checksum failed when using sha512: wanted sha512-JcaccaRCcK/A4c0igPQ9RCw91cil7pLhogDVmrThEvP20B/vbFaaNlmn3frF7pWeo3lATUiNrxVfgxm9qfr9GA== but got sha512-FDlyR8SyHQ0Ek38qBx5Hg/AwPuBI/1w/QWpMgzw19Vn81xsDNFTOXJpU0HcvI78C72wwXjJ3T7+EX7k2geDV4Q==. (7553 bytes)
[0] 
[0] npm ERR! A complete log of this run can be found in:
[0] npm ERR!     /home/gitpod/.npm/_logs/2024-04-17T19_26_12_354Z-debug.log
```

Error in 3007:
```
Server Error
Error: Module not found: Can't resolve '@deep-foundation/deeplinks/imports/client'
  1 |
> 2 | import { DeepNamespaceProvider, DeepProvider, useDeep } from '@deep-foundation/deeplinks/imports/client';
  3 | import { Id, Link, MinilinksProvider, useMinilinksFilter } from '@deep-foundation/deeplinks/imports/minilinks';
  4 | import dynamic from "next/dynamic";
  5 | import React, { useCallback, useEffect, useRef, useState } from 'react';

https://nextjs.org/docs/messages/module-not-found

This error happened while generating the page. Any console logs will be displayed in the terminal window.
Call Stack
<unknown>
https://nextjs.org/docs/messages/module-not-found
<unknown>
https://nextjs.org/docs/messages/module-not-found
getNotFoundError
file:///workspace/dev/node_modules/next/dist/build/webpack/plugins/wellknown-errors-plugin/parseNotFoundError.js (120:16)
process.processTicksAndRejections
node:internal/process/task_queues (95:5)
async getModuleBuildError
file:///workspace/dev/node_modules/next/dist/build/webpack/plugins/wellknown-errors-plugin/webpackModuleError.js (102:27)
async
file:///workspace/dev/node_modules/next/dist/build/webpack/plugins/wellknown-errors-plugin/index.js (29:49)
async
file:///workspace/dev/node_modules/next/dist/build/webpack/plugins/wellknown-errors-plugin/index.js (27:21)
```
![image](https://github.com/deep-foundation/dev/assets/83237728/4a4e6624-32a1-4757-8f4d-2735b8aa35b0)

Error in 4000:
```
Failed to compile
./pages/_app.js:1:0
Module not found: Can't resolve 'next-i18next'
> 1 | import { appWithTranslation } from 'next-i18next';
  2 | import { Provider } from '../src/provider';
  3 |
  4 | function App({ Component, pageProps }) {

https://nextjs.org/docs/messages/module-not-found
This error occurred during the build process and can only be dismissed by fixing the error.
```
![image](https://github.com/deep-foundation/dev/assets/83237728/684d0b88-b3c0-40b5-8923-b26a9640708f)

**Comment by Konard** [comment]
# Workaround 1

Execute `npm ci` second time and then restart SDK in Gitpod
```
cd packages/sdk
npm ci
```

**Comment by Konard** [comment]
![Screenshot_20240420_220337](https://github.com/deep-foundation/dev/assets/1431904/7ce7a919-59ce-4a42-b3ce-108390753fae)
```
[0] npm WARN tarball tarball data for three-bmfont-text@git+ssh://git@github.com/dmarcos/three-bmfont-text.git#eed4878795be9b3e38cf6aec6b903f56acd1f695 (sha512-JcaccaRCcK/A4c0igPQ9RCw91cil7pLhogDVmrThEvP20B/vbFaaNlmn3frF7pWeo3lATUiNrxVfgxm9qfr9GA==) seems to be corrupted. Trying again.
[0] npm ERR! code EINTEGRITY
[0] npm ERR! sha512-JcaccaRCcK/A4c0igPQ9RCw91cil7pLhogDVmrThEvP20B/vbFaaNlmn3frF7pWeo3lATUiNrxVfgxm9qfr9GA== integrity checksum failed when using sha512: wanted sha512-JcaccaRCcK/A4c0igPQ9RCw91cil7pLhogDVmrThEvP20B/vbFaaNlmn3frF7pWeo3lATUiNrxVfgxm9qfr9GA== but got sha512-FDlyR8SyHQ0Ek38qBx5Hg/AwPuBI/1w/QWpMgzw19Vn81xsDNFTOXJpU0HcvI78C72wwXjJ3T7+EX7k2geDV4Q==. (7553 bytes)
[0] 
[0] npm ERR! A complete log of this run can be found in:
npm ERR!     /home/konard/.npm/_logs/2024-04-20T15_52_49_294Z-debug.log
[0] echo "packages/hasura npm ci" && cd /home/konard/Archive/Code/Deep/dev/packages/hasura && npm ci && cd ../.. && echo "packages/sdk npm ci" && cd /home/konard/Archive/Code/Deep/dev/packages/sdk && npm ci && cd ../.. && echo "packages/gh-pages npm ci" && cd /home/konard/Archive/Code/Deep/dev/packages/gh-pages && npm ci && cd ../.. && echo "packages/materialized-path npm ci" && cd /home/konard/Archive/Code/Deep/dev/packages/materialized-path && npm ci && cd ../.. && echo "packages/store npm ci" && cd /home/konard/Archive/Code/Deep/dev/packages/store && npm ci && cd ../.. && echo "packages/react-hasura npm ci" && cd /home/konard/Archive/Code/Deep/dev/packages/react-hasura && npm ci && cd ../.. && echo "packages/js-docker-isolation-provider npm ci" && cd /home/konard/Archive/Code/Deep/dev/packages/js-docker-isolation-provider && npm ci && cd ../.. && echo "packages/npm-packager npm ci" && cd /home/konard/Archive/Code/Deep/dev/packages/npm-packager && npm ci && cd ../.. && echo "packages/deep-memo-app npm ci" && cd /home/konard/Archive/Code/Deep/dev/packages/deep-memo-app && npm ci && cd ../.. && echo "packages/deep-memo npm ci" && cd /home/konard/Archive/Code/Deep/dev/packages/deep-memo && npm ci exited with code 1
[18:52:49] 'packages:ci' errored after 38 s
[18:52:49] Error: [object Object]
    at formatError (/home/konard/Archive/Code/Deep/dev/node_modules/gulp-cli/lib/versioned/^4.0.0/format-error.js:21:10)
    at Gulp.<anonymous> (/home/konard/Archive/Code/Deep/dev/node_modules/gulp-cli/lib/versioned/^4.0.0/log/events.js:33:15)
    at Gulp.emit (node:events:525:35)
    at Gulp.emit (node:domain:489:12)
    at Object.error (/home/konard/Archive/Code/Deep/dev/node_modules/undertaker/lib/helpers/createExtensions.js:61:10)
    at handler (/home/konard/Archive/Code/Deep/dev/node_modules/now-and-later/lib/map.js:50:14)
    at f (/home/konard/Archive/Code/Deep/dev/node_modules/once/once.js:25:25)
    at f (/home/konard/Archive/Code/Deep/dev/node_modules/once/once.js:25:25)
    at tryCatch (/home/konard/Archive/Code/Deep/dev/node_modules/async-done/index.js:24:15)
    at done (/home/konard/Archive/Code/Deep/dev/node_modules/async-done/index.js:40:12)
```

**Comment by Konard** [comment]
Fixed at https://github.com/deep-foundation/dev/commit/5f4b2b78e97ead666ca5946729f9bf7cec4b3caa

**Comment by Konard** [comment]
# Solution

```bash
rm -rf node_modules
rm -f package-lock.json
npm i
```
