### ISSUE TITLE
Get falal error from git while runing 'npm run packages'

### ISSUE THREAD

**Issue by netkeep80** [deep-foundation/dev#231]
### Bug description

roman@Ubuntu20:~/github.com/deep-foundation/dev$ npm run packages

> @deep-foundation/dev@0.0.21 packages
> (npx gulp packages:get) && (npx gulp packages:ci)

[15:32:12] Requiring external module ts-node/register
[15:32:13] Using gulpfile ~/github.com/deep-foundation/dev/gulpfile.ts
[15:32:13] Starting 'packages:get'...
[15:42:03] 'packages:get' errored after 9.82 min
[15:42:03] Error: Cloning into '/home/roman/github.com/deep-foundation/dev/packages/deep-memo-app'...
fatal: the remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed
fatal: clone of 'https://github.com/deep-foundation/deep-memo-app' into submodule path '/home/roman/github.com/deep-foundation/dev/packages/deep-memo-app' failed
Failed to clone 'packages/deep-memo-app'. Retry scheduled
Cloning into '/home/roman/github.com/deep-foundation/dev/packages/deepcase-app'...
fatal: the remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed
fatal: clone of 'https://github.com/deep-foundation/deepcase-app' into submodule path '/home/roman/github.com/deep-foundation/dev/packages/deepcase-app' failed
Failed to clone 'packages/deepcase-app'. Retry scheduled
Cloning into '/home/roman/github.com/deep-foundation/dev/packages/deeplinks'...
fatal: the remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed
fatal: clone of 'https://github.com/deep-foundation/deeplinks.git' into submodule path '/home/roman/github.com/deep-foundation/dev/packages/deeplinks' failed
Failed to clone 'packages/deeplinks'. Retry scheduled
Cloning into '/home/roman/github.com/deep-foundation/dev/packages/gh-pages'...
fatal: the remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed
fatal: clone of 'https://github.com/deep-foundation/deepcase.github.io.git' into submodule path '/home/roman/github.com/deep-foundation/dev/packages/gh-pages' failed
Failed to clone 'packages/gh-pages'. Retry scheduled
Cloning into '/home/roman/github.com/deep-foundation/dev/packages/sdk'...
fatal: the remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed
fatal: clone of 'https://github.com/deep-foundation/sdk.git' into submodule path '/home/roman/github.com/deep-foundation/dev/packages/sdk' failed
Failed to clone 'packages/sdk'. Retry scheduled
Cloning into '/home/roman/github.com/deep-foundation/dev/packages/deep-memo-app'...
fatal: the remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed
fatal: clone of 'https://github.com/deep-foundation/deep-memo-app' into submodule path '/home/roman/github.com/deep-foundation/dev/packages/deep-memo-app' failed
Failed to clone 'packages/deep-memo-app' a second time, aborting

    at Object.action (/home/roman/github.com/deep-foundation/dev/node_modules/simple-git/src/lib/plugins/error-detection.plugin.ts:38:28)
    at PluginStore.exec (/home/roman/github.com/deep-foundation/dev/node_modules/simple-git/src/lib/plugins/plugin-store.ts:24:29)
    at /home/roman/github.com/deep-foundation/dev/node_modules/simple-git/src/lib/runners/git-executor-chain.ts:114:40
    at new Promise (<anonymous>)
    at GitExecutorChain.handleTaskData (/home/roman/github.com/deep-foundation/dev/node_modules/simple-git/src/lib/runners/git-executor-chain.ts:111:14)
    at GitExecutorChain.<anonymous> (/home/roman/github.com/deep-foundation/dev/node_modules/simple-git/src/lib/runners/git-executor-chain.ts:88:40)
    at Generator.next (<anonymous>)
    at fulfilled (/home/roman/github.com/deep-foundation/dev/node_modules/simple-git/src/lib/runners/git-executor-chain.js:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)

### Workaround

Local usage
Installation

Install node 18 (we recommend to use [nvm](https://github.com/nvm-sh/nvm#installing-and-updating))

Install docker and docker-compose
If you have Docker Desktop with docker compose (not docker-compose) you should enable this setting in Docker Desktop: image Or use this command (if your are on linux):

echo 'docker compose --compatibility "$@"' | sudo tee -a /usr/local/bin/docker-compose && sudo chmod +x /usr/local/bin/docker-compose

[Install docker on Ubuntu](https://docs.docker.com/engine/install/ubuntu/) or use this commands:

sudo apt update
sudo apt install -y git curl docker.io docker-compose

Optionally set up docker group and add user to this group (it may be done automatically on installation):

sudo groupadd docker
sudo usermod -aG docker $(whoami)

These commands must be able to run without sudo, if it is not the case restart computer or relogin as user.

docker run hello-world
docker rm $(docker ps -a -q --filter "ancestor=hello-world")
docker image rm hello-world

Run this script to initialize and launch deep

git clone https://github.com/deep-foundation/dev.git
cd dev
npm ci
rm -rf packages/deepcase
rm -rf packages/deepcase-app
rm -rf packages/deeplinks
npm run packages

### Environment

```shell
Linux Ubuntu20 5.15.0-91-generic #101~20.04.1-Ubuntu SMP Thu Nov 16 14:22:28 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux


roman@Ubuntu20:~/github.com/deep-foundation/dev$ git show
commit 18207b70274d637b1e081cf63054e1b95dd41171 (HEAD -> main, origin/main, origin/HEAD)
Author: Konstantin Dyachenko <drakonard@gmail.com>
Date:   Fri May 3 01:19:12 2024 +0000

    sync

diff --git a/package-lock.json b/package-lock.json
index ba987f3..a580692 100644
--- a/package-lock.json
+++ b/package-lock.json
@@ -53383,7 +53383,7 @@
     },
     "packages/deepcase": {
       "name": "@deep-foundation/deepcase",
-      "version": "0.0.115",
+      "version": "0.0.118",
       "license": "Unlicense",
       "dependencies": {
         "@amcharts/amcharts5": "^5.5.1",
@@ -53480,14 +53480,14 @@
         "node": "^18"
       },
       "peerDependencies": {
-        "@deep-foundation/deeplinks": "0.0.*",
+        "@deep-foundation/deeplinks": "0.0.x",
         "next": "^14.2.2",
         "react": "*"
       }
     },
     "packages/deepcase-app": {
       "name": "@deep-foundation/deepcase-app",
-      "version": "0.1.0-beta.18",
+      "version": "0.1.0-beta.19",
       "license": "Unlicense",
       "dependencies": {
         "@builder.io/partytown": "^0.8.2",
@@ -54052,7 +54052,7 @@
     },
     "packages/deeplinks": {
       "name": "@deep-foundation/deeplinks",
-      "version": "0.0.338",
+      "version": "0.0.340",
       "license": "Unlicense",
       "dependencies": {
         "@chainsafe/libp2p-yamux": "^6.0.2",
diff --git a/packages/deepcase b/packages/deepcase
index cf7d2f4..78df971 160000
--- a/packages/deepcase
+++ b/packages/deepcase
@@ -1 +1 @@
-Subproject commit cf7d2f4a834d8de8270b97705cefb6e89b3f5ed0
```

**Comment by netkeep80** [comment]
Можно уменьшить объем скачиваемых сабмодулей используя git clone --depth 1
