### ISSUE TITLE
npm ERR! code EINTEGRITY

### ISSUE THREAD

**Issue by TimaxLacs** [deep-foundation/dev#232]
Ошибка при выполнении команды `npm run packages` при попытке установить локальный Deep на пк:
```
[0] npm ERR! code EINTEGRITY
[0] npm ERR! sha512-FDlyR8SyHQ0Ek38qBx5Hg/AwPuBI/1w/QWpMgzw19Vn81xsDNFTOXJpU0HcvI78C72wwXjJ3T7+EX7k2geDV4Q== integrity checksum failed when using sha512: wanted sha512-FDlyR8SyHQ0Ek38qBx5Hg/AwPuBI/1w/QWpMgzw19Vn81xsDNFTOXJpU0HcvI78C72wwXjJ3T7+EX7k2geDV4Q== but got sha512-JcaccaRCcK/A4c0igPQ9RCw91cil7pLhogDVmrThEvP20B/vbFaaNlmn3frF7pWeo3lATUiNrxVfgxm9qfr9GA==. (7597 bytes)
[0] 
[0] npm ERR! A complete log of this run can be found in:
[0] npm ERR!     /home/timax/.npm/_logs/2024-05-20T03_22_10_469Z-debug.log
[0] echo "packages/hasura npm ci" && cd /home/timax/Code/Deep-project/Local-Deep/dev/packages/hasura && npm ci && cd ../.. && echo "packages/sdk npm ci" && cd /home/timax/Code/Deep-project/Local-Deep/dev/packages/sdk && npm ci && cd ../.. && echo "packages/gh-pages npm ci" && cd /home/timax/Code/Deep-project/Local-Deep/dev/packages/gh-pages && npm ci && cd ../.. && echo "packages/materialized-path npm ci" && cd /home/timax/Code/Deep-project/Local-Deep/dev/packages/materialized-path && npm ci && cd ../.. && echo "packages/store npm ci" && cd /home/timax/Code/Deep-project/Local-Deep/dev/packages/store && npm ci && cd ../.. && echo "packages/react-hasura npm ci" && cd /home/timax/Code/Deep-project/Local-Deep/dev/packages/react-hasura && npm ci && cd ../.. && echo "packages/js-docker-isolation-provider npm ci" && cd /home/timax/Code/Deep-project/Local-Deep/dev/packages/js-docker-isolation-provider && npm ci && cd ../.. && echo "packages/npm-packager npm ci" && cd /home/timax/Code/Deep-project/Local-Deep/dev/packages/npm-packager && npm ci && cd ../.. && echo "packages/deep-memo-app npm ci" && cd /home/timax/Code/Deep-project/Local-Deep/dev/packages/deep-memo-app && npm ci && cd ../.. && echo "packages/deep-memo npm ci" && cd /home/timax/Code/Deep-project/Local-Deep/dev/packages/deep-memo && npm ci exited with code 1
[06:22:10] 'packages:ci' errored after 2.63 min
[06:22:11] Error: [object Object]
    at formatError (/home/timax/Code/Deep-project/Local-Deep/dev/node_modules/gulp-cli/lib/versioned/^4.0.0/format-error.js:21:10)
    at Gulp.<anonymous> (/home/timax/Code/Deep-project/Local-Deep/dev/node_modules/gulp-cli/lib/versioned/^4.0.0/log/events.js:33:15)
    at Gulp.emit (node:events:529:35)
    at Gulp.emit (node:domain:489:12)
    at Object.error (/home/timax/Code/Deep-project/Local-Deep/dev/node_modules/undertaker/lib/helpers/createExtensions.js:61:10)
    at handler (/home/timax/Code/Deep-project/Local-Deep/dev/node_modules/now-and-later/lib/map.js:50:14)
    at f (/home/timax/Code/Deep-project/Local-Deep/dev/node_modules/once/once.js:25:25)
    at f (/home/timax/Code/Deep-project/Local-Deep/dev/node_modules/once/once.js:25:25)
    at tryCatch (/home/timax/Code/Deep-project/Local-Deep/dev/node_modules/async-done/index.js:24:15)
```

**Comment by Konard** [comment]
# Solution

```
cd packages/sdk/
npm run package:refresh
```

**Comment by Konard** [comment]
Find the dependency with a problem:

```bash
npm list three-bmfont-text
```

**Comment by Konard** [comment]
This issue continue to repeat.

**Comment by Konard** [comment]
# Solution 1

```bash
npm i -g npm@latest
```

**Comment by Konard** [comment]
Regression detected at https://github.com/deep-foundation/dev/commit/17fc2ab0d22e7f4735136ad31255c2b322da8905

**Comment by Konard** [comment]
Attempting to fix regression using `npm run packages:refresh` command at https://github.com/deep-foundation/dev/commit/66390be80c9768d5f3ff9b28d9b2cc11c0baaa14

This error may be connected to difference between versions of node.js itself, using latest version of npm is not enough by itself.

Versions at the moment of commit:
```
gitpod /workspace/dev (main) $ node -v
v18.17.1
gitpod /workspace/dev (main) $ npm -v
10.8.1
```

**Comment by Konard** [comment]
Fixed at https://github.com/deep-foundation/dev/commit/66390be80c9768d5f3ff9b28d9b2cc11c0baaa14

**Comment by Konard** [comment]
Updated a way GitPod makes prebuild:

- https://github.com/deep-foundation/dev/commit/2ec9998f130ff06a4b7dc5d62f28552af584edd1
- https://github.com/deep-foundation/dev/commit/9321f31107c749d29b0e7e013f42c7bfc5276360
- https://github.com/deep-foundation/dev/commit/e7c58b57904e3fc015cae98c32ab7cfca4609657
- https://github.com/deep-foundation/dev/commit/9a0054c99072e84841f546d30230532927a127f7

**Comment by Konard** [comment]
On prebuild we have correct version, and that makes Deep instance in GitPod work:

```
Making sure correct versions of node and nvm are used...
=> nvm is already installed in /home/gitpod/.nvm, trying to update using git

=> => Compressing and cleaning up git repository

=> Appending nvm source string to /home/gitpod/.bashrc
=> Appending bash_completion source string to /home/gitpod/.bashrc
=> Installing Node.js version 18.17.1
Now using node v18.17.1 (npm v9.6.7)
=> Node.js version 18.17.1 has been successfully installed
=> Close and reopen your terminal to start using nvm or run the following to use it now:

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
Found '/workspace/dev/.nvmrc' with version <18>
Downloading and installing node v18.20.3...
Now using node v18.20.3 (npm v10.7.0)
Found '/workspace/dev/.nvmrc' with version <18>
Now using node v18.20.3 (npm v10.7.0)

removed 2 packages, and changed 63 packages in 2s

24 packages are looking for funding
  run `npm fund` for details
Applied versions of node and npm:
v18.20.3
10.8.1
```

But after GitPod starts using that prebuild we again have old versions:

```
gitpod /workspace/dev (main) $ node -v && npm -v
v18.17.1
9.6.7
```

**Comment by Konard** [comment]
We may try to use

```bash
. ~/.nvm/nvm.sh
```

Source: https://unix.stackexchange.com/questions/184508/nvm-command-not-available-in-bash-script
