### ISSUE TITLE
Traceback (most recent call last):

### ISSUE THREAD

**Issue by TimaxLacs** [deep-foundation/dev#233]
Ошибка возинкает при попытке установить локальный дип на этапе запуска команды `npm run local`
```
Traceback (most recent call last):
[2]   File "/usr/bin/docker-compose", line 33, in <module>
[2]     sys.exit(load_entry_point('docker-compose==1.29.2', 'console_scripts', 'docker-compose')())
[2]   File "/usr/bin/docker-compose", line 25, in importlib_load_entry_point
[2]     return next(matches).load()
[2]   File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 171, in load
[2]     module = import_module(match.group('module'))
[2]   File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
[2]     return _bootstrap._gcd_import(name[level:], package, level)
[2]   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
[2]   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
[2]   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
[2]   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
[2]   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
[2]   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
[2]   File "/usr/lib/python3/dist-packages/compose/cli/main.py", line 19, in <module>
[2]     from ..config import ConfigurationError
[2]   File "/usr/lib/python3/dist-packages/compose/config/__init__.py", line 3, in <module>
[2]     from .config import ConfigurationError
[2]   File "/usr/lib/python3/dist-packages/compose/config/config.py", line 19, in <module>
[2]     from . import types
[2]   File "/usr/lib/python3/dist-packages/compose/config/types.py", line 10, in <module>
[2]     from docker.utils.ports import build_port_bindings
[2] ModuleNotFoundError: No module named 'docker.utils.ports'
[2] npm run local-engine exited with code 1
[1] 
[1] > @deep-foundation/deeplinks@0.0.348 package:build
[1] > tsc --project tsconfig.json
```

**Comment by TimaxLacs** [comment]
ошибка появляется после игнорирования этой ошибки https://github.com/deep-foundation/dev/issues/232
