### ISSUE TITLE
I can't install deep in production. Need check instruction

### ISSUE THREAD

**Issue by suenot** [deep-foundation/dev#234]
### Bug description

I have errors when run https://gist.github.com/suenot/7f3a505aa385b7e0be7d143c5d2723e4:
```
{
  "operation": "run",
  "envs": {
    "DEEPLINKS_PUBLIC_URL": "https://deeplinks.app.marketmaker.cc",
    "NEXT_PUBLIC_DEEPLINKS_URL": "https://deeplinks.app.marketmaker.cc",
    "NEXT_PUBLIC_GQL_PATH": "deeplinks.app.marketmaker.cc/gql",
    "NEXT_PUBLIC_GQL_SSL": "1",
    "NEXT_PUBLIC_DEEPLINKS_SERVER": "https://deepcase.app.marketmaker.cc",
    "NEXT_PUBLIC_ENGINES_ROUTE": "0",
    "NEXT_PUBLIC_DISABLE_CONNECTOR": "1",
    "JWT_SECRET": "'{\"type\":\"HS256\",\"key\":\"7QeCG04mzT5fkfIGMRpi4UWLxu6RExtvvu9enhkKQAXbVzFJ9y6ATYRI2+YaR/1mWMw=\"}'",
    "DEEPLINKS_HASURA_STORAGE_URL": "http://host.docker.internal:8000/",
    "HASURA_GRAPHQL_ADMIN_SECRET": "585f276cb1061a0c7708fd61e35185c80611779287b8201e",
    "MIGRATIONS_HASURA_SECRET": "585f276cb1061a0c7708fd61e35185c80611779287b8201e",
    "DEEPLINKS_HASURA_SECRET": "585f276cb1061a0c7708fd61e35185c80611779287b8201e",
    "POSTGRES_PASSWORD": "07609f230b0f87676f39267da1b86d297e45b1f13b7b82d5",
    "HASURA_GRAPHQL_DATABASE_URL": "postgres://postgres:07609f230b0f87676f39267da1b86d297e45b1f13b7b82d5@postgres:5432/postgres",
    "POSTGRES_MIGRATIONS_SOURCE": "postgres://postgres:07609f230b0f87676f39267da1b86d297e45b1f13b7b82d5@host.docker.internal:5432/postgres?sslmode=disable",
    "RESTORE_VOLUME_FROM_SNAPSHOT": "0",
    "MANUAL_MIGRATIONS": "1",
    "MINIO_ROOT_USER": "ac8c40ce924d5a5211c1ffbd30d4294cd4693dd05cbcc586",
    "MINIO_ROOT_PASSWORD": "26c9f5f2239ccab16203eb897aa6607d74e890d3d0375e63",
    "S3_ACCESS_KEY": "ac8c40ce924d5a5211c1ffbd30d4294cd4693dd05cbcc586",
    "S3_SECRET_KEY": "26c9f5f2239ccab16203eb897aa6607d74e890d3d0375e63"
  }
}
CONTAINER ID   IMAGE     COMMAND   CREATED   STATUS    PORTS     NAMES
__dirname /root/.nvm/versions/node/v18.20.2/lib/node_modules/@deep-foundation/deeplinks/imports
rootDir /root/.nvm/versions/node/v18.20.2/lib/node_modules/@deep-foundation/deeplinks
  deeplinks:engine:error Error: connect ECONNREFUSED 127.0.0.1:3006
  deeplinks:engine:error     at AxiosError.from (/root/.nvm/versions/node/v18.20.2/lib/node_modules/@deep-foundation/deeplinks/node_modules/axios/dist/node/axios.cjs:836:14)
  deeplinks:engine:error     at RedirectableRequest.handleRequestError (/root/.nvm/versions/node/v18.20.2/lib/node_modules/@deep-foundation/deeplinks/node_modules/axios/dist/node/axios.cjs:3086:25)
  deeplinks:engine:error     at RedirectableRequest.emit (node:events:529:35)
  deeplinks:engine:error     at eventHandlers.<computed> (/root/.nvm/versions/node/v18.20.2/lib/node_modules/@deep-foundation/deeplinks/node_modules/follow-redirects/index.js:38:24)
  deeplinks:engine:error     at ClientRequest.emit (node:events:517:28)
  deeplinks:engine:error     at Socket.socketErrorListener (node:_http_client:501:9)
  deeplinks:engine:error     at Socket.emit (node:events:517:28)
  deeplinks:engine:error     at emitErrorNT (node:internal/streams/destroy:151:8)
  deeplinks:engine:error     at emitErrorCloseNT (node:internal/streams/destroy:116:3)
  deeplinks:engine:error     at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
  deeplinks:engine:error     at Axios.request (/root/.nvm/versions/node/v18.20.2/lib/node_modules/@deep-foundation/deeplinks/node_modules/axios/dist/node/axios.cjs:3876:41)
  deeplinks:engine:error     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
  deeplinks:engine:error     at async _checkDeeplinksStatus (/root/.nvm/versions/node/v18.20.2/lib/node_modules/@deep-foundation/deeplinks/imports/engine-server.cjs:205:14)
  deeplinks:engine:error     at async call (/root/.nvm/versions/node/v18.20.2/lib/node_modules/@deep-foundation/deeplinks/imports/engine-server.cjs:359:29)
  deeplinks:engine:error     at async /root/.nvm/versions/node/v18.20.2/lib/node_modules/@deep-foundation/deeplinks/call.cjs:8:3 +0ms
  deeplinks:engine:error Error: connect ECONNREFUSED 127.0.0.1:3007
  deeplinks:engine:error     at AxiosError.from (/root/.nvm/versions/node/v18.20.2/lib/node_modules/@deep-foundation/deeplinks/node_modules/axios/dist/node/axios.cjs:836:14)
  deeplinks:engine:error     at RedirectableRequest.handleRequestError (/root/.nvm/versions/node/v18.20.2/lib/node_modules/@deep-foundation/deeplinks/node_modules/axios/dist/node/axios.cjs:3086:25)
  deeplinks:engine:error     at RedirectableRequest.emit (node:events:529:35)
  deeplinks:engine:error     at eventHandlers.<computed> (/root/.nvm/versions/node/v18.20.2/lib/node_modules/@deep-foundation/deeplinks/node_modules/follow-redirects/index.js:38:24)
  deeplinks:engine:error     at ClientRequest.emit (node:events:517:28)
  deeplinks:engine:error     at Socket.socketErrorListener (node:_http_client:501:9)
  deeplinks:engine:error     at Socket.emit (node:events:517:28)
  deeplinks:engine:error     at emitErrorNT (node:internal/streams/destroy:151:8)
  deeplinks:engine:error     at emitErrorCloseNT (node:internal/streams/destroy:116:3)
  deeplinks:engine:error     at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
  deeplinks:engine:error     at Axios.request (/root/.nvm/versions/node/v18.20.2/lib/node_modules/@deep-foundation/deeplinks/node_modules/axios/dist/node/axios.cjs:3876:41)
  deeplinks:engine:error     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
  deeplinks:engine:error     at async _checkDeepcaseStatus (/root/.nvm/versions/node/v18.20.2/lib/node_modules/@deep-foundation/deeplinks/imports/engine-server.cjs:219:14)
  deeplinks:engine:error     at async call (/root/.nvm/versions/node/v18.20.2/lib/node_modules/@deep-foundation/deeplinks/imports/engine-server.cjs:360:28)
  deeplinks:engine:error     at async /root/.nvm/versions/node/v18.20.2/lib/node_modules/@deep-foundation/deeplinks/call.cjs:8:3 +5ms
MIGRATIONS_DIR /tmp/deep
```

**Comment by suenot** [comment]
Connected issue: https://github.com/deep-foundation/deeplinks/issues/337
