### ISSUE TITLE
npm ERR! code EINTEGRITY

### ISSUE THREAD

**Issue by Konard** [deep-foundation/dev#236]
```
gitpod /workspace/empty/dev (main) $ npm run packages

> @deep-foundation/dev@0.0.21 packages
> rm -rf packages/deepcase && rm -rf packages/deepcase-app && rm -rf packages/deeplinks && (npx gulp packages:get) && (npx gulp packages:ci)

[03:51:06] Requiring external module ts-node/register
[03:51:08] Using gulpfile /workspace/empty/dev/gulpfile.ts
[03:51:08] Starting 'packages:get'...
[0] Your branch is up to date with 'origin/main'.
[0] Switched to branch 'main'
[1] Your branch is up to date with 'origin/main'.
[1] Switched to branch 'main'
[2] Your branch is up to date with 'origin/main'.
[2] Switched to branch 'main'
[6] Your branch is up to date with 'origin/main'.
[6] Switched to branch 'main'
[7] Your branch is up to date with 'origin/main'.
[7] Switched to branch 'main'
[8] Your branch is up to date with 'origin/main'.
[8] Switched to branch 'main'
[9] Your branch is up to date with 'origin/main'.
[9] Switched to branch 'main'
[10] Your branch is up to date with 'origin/main'.
[10] Switched to branch 'main'
[11] Your branch is up to date with 'origin/main'.
[11] Switched to branch 'main'
[12] Your branch is up to date with 'origin/main'.
[12] Switched to branch 'main'
[12] cd /workspace/empty/dev/packages/npm-packager && git checkout main exited with code 0
[11] cd /workspace/empty/dev/packages/workflows && git checkout main exited with code 0
[10] cd /workspace/empty/dev/packages/python-docker-isolation-provider && git checkout main exited with code 0
[9] cd /workspace/empty/dev/packages/js-docker-isolation-provider && git checkout main exited with code 0
[8] cd /workspace/empty/dev/packages/react-hasura && git checkout main exited with code 0
[7] cd /workspace/empty/dev/packages/store && git checkout main exited with code 0
[6] cd /workspace/empty/dev/packages/materialized-path && git checkout main exited with code 0
[2] cd /workspace/empty/dev/packages/deepcase && git checkout main exited with code 0
[1] cd /workspace/empty/dev/packages/deeplinks && git checkout main exited with code 0
[0] cd /workspace/empty/dev/packages/hasura && git checkout main exited with code 0
[14] Switched to branch 'main'
[14] Your branch is up to date with 'origin/main'.
[14] cd /workspace/empty/dev/packages/deep-memo && git checkout main exited with code 0
[5] Switched to branch 'main'
[5] Your branch is up to date with 'origin/main'.
[5] cd /workspace/empty/dev/packages/gh-pages && git checkout main exited with code 0
[4] Switched to branch 'main'
[4] Your branch is up to date with 'origin/main'.
[4] cd /workspace/empty/dev/packages/sdk && git checkout main exited with code 0
[3] Switched to branch 'main'
[3] Your branch is up to date with 'origin/main'.
[3] cd /workspace/empty/dev/packages/deepcase-app && git checkout main exited with code 0
[13] Switched to branch 'main'
[13] Your branch is up to date with 'origin/main'.
[13] cd /workspace/empty/dev/packages/deep-memo-app && git checkout main exited with code 0
[03:51:41] Finished 'packages:get' after 33 s
[03:51:41] Requiring external module ts-node/register
[03:51:43] Using gulpfile /workspace/empty/dev/gulpfile.ts
[03:51:43] Starting 'packages:ci'...
command echo "packages/hasura npm ci" && cd /workspace/empty/dev/packages/hasura && npm ci && cd ../.. && echo "packages/sdk npm ci" && cd /workspace/empty/dev/packages/sdk && npm ci && cd ../.. && echo "packages/gh-pages npm ci" && cd /workspace/empty/dev/packages/gh-pages && npm ci && cd ../.. && echo "packages/materialized-path npm ci" && cd /workspace/empty/dev/packages/materialized-path && npm ci && cd ../.. && echo "packages/store npm ci" && cd /workspace/empty/dev/packages/store && npm ci && cd ../.. && echo "packages/react-hasura npm ci" && cd /workspace/empty/dev/packages/react-hasura && npm ci && cd ../.. && echo "packages/js-docker-isolation-provider npm ci" && cd /workspace/empty/dev/packages/js-docker-isolation-provider && npm ci && cd ../.. && echo "packages/npm-packager npm ci" && cd /workspace/empty/dev/packages/npm-packager && npm ci && cd ../.. && echo "packages/deep-memo-app npm ci" && cd /workspace/empty/dev/packages/deep-memo-app && npm ci && cd ../.. && echo "packages/deep-memo npm ci" && cd /workspace/empty/dev/packages/deep-memo && npm ci
[0] packages/hasura npm ci
[0] npm WARN deprecated boom@7.3.0: This module has moved and is now available at @hapi/boom. Please update your dependencies as this version is no longer maintained an may contain bugs and security issues.
[0] npm WARN deprecated apollo-datasource@0.10.0: The `apollo-datasource` package is part of Apollo Server v2 and v3, which are now deprecated (end-of-life October 22nd 2023 and October 22nd 2024, respectively). See https://www.apollographql.com/docs/apollo-server/previous-versions/ for more details.
[0] npm WARN deprecated hoek@6.1.3: This module has moved and is now available at @hapi/hoek. Please update your dependencies as this version is no longer maintained an may contain bugs and security issues.
[0] npm WARN deprecated apollo-tracing@0.16.0: The `apollo-tracing` package is no longer part of Apollo Server 3. See https://www.apollographql.com/docs/apollo-server/migration/#tracing for details
[0] npm WARN deprecated apollo-server-plugin-base@0.14.0: The `apollo-server-plugin-base` package is part of Apollo Server v2 and v3, which are now deprecated (end-of-life October 22nd 2023 and October 22nd 2024, respectively). This package's functionality is now found in the `@apollo/server` package. See https://www.apollographql.com/docs/apollo-server/previous-versions/ for more details.
[0] npm WARN deprecated accept@3.1.3: This module has moved and is now available at @hapi/accept. Please update your dependencies as this version is no longer maintained an may contain bugs and security issues.
[0] npm WARN deprecated apollo-server-types@0.10.0: The `apollo-server-types` package is part of Apollo Server v2 and v3, which are now deprecated (end-of-life October 22nd 2023 and October 22nd 2024, respectively). This package's functionality is now found in the `@apollo/server` package. See https://www.apollographql.com/docs/apollo-server/previous-versions/ for more details.
[0] npm WARN deprecated graphql-extensions@0.16.0: The `graphql-extensions` API has been removed from Apollo Server 3. Use the plugin API instead: https://www.apollographql.com/docs/apollo-server/integrations/plugins/
[0] npm WARN deprecated apollo-server-errors@2.5.0: The `apollo-server-errors` package is part of Apollo Server v2 and v3, which are now deprecated (end-of-life October 22nd 2023 and October 22nd 2024, respectively). This package's functionality is now found in the `@apollo/server` package. See https://www.apollographql.com/docs/apollo-server/previous-versions/ for more details.
[0] npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
[0] npm WARN deprecated apollo-cache-control@0.15.0: The functionality provided by the `apollo-cache-control` package is built in to `apollo-server-core` starting with Apollo Server 3. See https://www.apollographql.com/docs/apollo-server/migration/#cachecontrol for details.
[0] npm WARN deprecated apollo-server-caching@0.7.0: This package is part of the legacy caching implementation used by Apollo Server v2 and v3, and is no longer maintained. We recommend you switch to the newer Keyv-based implementation (which is compatible with all versions of Apollo Server). See https://www.apollographql.com/docs/apollo-server/v3/performance/cache-backends#legacy-caching-implementation for more details.
[0] npm WARN deprecated apollo-server-micro@2.26.2: The `apollo-server-micro` package is part of Apollo Server v2 and v3, which are now deprecated (end-of-life October 22nd 2023 and October 22nd 2024, respectively). This package's functionality is now found in the `@apollo/server` package. See https://www.apollographql.com/docs/apollo-server/previous-versions/ for more details.
[0] npm WARN deprecated apollo-reporting-protobuf@0.8.0: The `apollo-reporting-protobuf` package is part of Apollo Server v2 and v3, which are now deprecated (end-of-life October 22nd 2023 and October 22nd 2024, respectively). This package's functionality is now found in the `@apollo/usage-reporting-protobuf` package. See https://www.apollographql.com/docs/apollo-server/previous-versions/ for more details.
[0] npm WARN deprecated apollo-server-env@3.2.0: The `apollo-server-env` package is part of Apollo Server v2 and v3, which are now deprecated (end-of-life October 22nd 2023 and October 22nd 2024, respectively). This package's functionality is now found in the `@apollo/utils.fetcher` package. See https://www.apollographql.com/docs/apollo-server/previous-versions/ for more details.
[0] npm WARN deprecated subscriptions-transport-ws@0.9.19: The `subscriptions-transport-ws` package is no longer maintained. We recommend you use `graphql-ws` instead. For help migrating Apollo software to `graphql-ws`, see https://www.apollographql.com/docs/apollo-server/data/subscriptions/#switching-from-subscriptions-transport-ws    For general help using `graphql-ws`, see https://github.com/enisdenjo/graphql-ws/blob/master/README.md
[0] npm WARN deprecated graphql-tools@4.0.8: This package has been deprecated and now it only exports makeExecutableSchema.
[0] npm WARN deprecated And it will no longer receive updates.
[0] npm WARN deprecated We recommend you to migrate to scoped packages such as @graphql-tools/schema, @graphql-tools/utils and etc.
[0] npm WARN deprecated Check out https://www.graphql-tools.com to learn what package you should use instead
[0] npm WARN deprecated apollo-server-core@2.26.2: The `apollo-server-core` package is part of Apollo Server v2 and v3, which are now deprecated (end-of-life October 22nd 2023 and October 22nd 2024, respectively). This package's functionality is now found in the `@apollo/server` package. See https://www.apollographql.com/docs/apollo-server/previous-versions/ for more details.
[0] npm WARN deprecated core-js@2.6.12: core-js@<3.23.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Some versions have web compatibility issues. Please, upgrade your dependencies to the actual version of core-js.
[0] 
[0] added 412 packages, and audited 413 packages in 4s
[0] 
[0] 66 packages are looking for funding
[0]   run `npm fund` for details
[0] 
[0] 15 vulnerabilities (1 moderate, 9 high, 5 critical)
[0] 
[0] To address issues that do not require attention, run:
[0]   npm audit fix
[0] 
[0] To address all issues possible (including breaking changes), run:
[0]   npm audit fix --force
[0] 
[0] Some issues need review, and may require choosing
[0] a different dependency.
[0] 
[0] Run `npm audit` for details.
[0] packages/sdk npm ci
[0] npm WARN EBADENGINE Unsupported engine {
[0] npm WARN EBADENGINE   package: '@deep-foundation/deepcase@0.0.110',
[0] npm WARN EBADENGINE   required: { node: '^18' },
npm WARN EBADENGINE   current: { node: 'v20.13.1', npm: '10.5.2' }
[0] npm WARN EBADENGINE }
[0] npm WARN EBADENGINE Unsupported engine {
[0] npm WARN EBADENGINE   package: '@deep-foundation/deeplinks@0.0.340',
[0] npm WARN EBADENGINE   required: { node: '^18' },
npm WARN EBADENGINE   current: { node: 'v20.13.1', npm: '10.5.2' }
[0] npm WARN EBADENGINE }
[0] npm WARN deprecated source-map-url@0.4.1: See https://github.com/lydell/source-map-url#deprecated
[0] npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
[0] npm WARN deprecated boom@7.3.0: This module has moved and is now available at @hapi/boom. Please update your dependencies as this version is no longer maintained an may contain bugs and security issues.
[0] npm WARN deprecated apollo-datasource@0.10.0: The `apollo-datasource` package is part of Apollo Server v2 and v3, which are now deprecated (end-of-life October 22nd 2023 and October 22nd 2024, respectively). See https://www.apollographql.com/docs/apollo-server/previous-versions/ for more details.
[0] npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
[0] npm WARN deprecated hoek@6.1.3: This module has moved and is now available at @hapi/hoek. Please update your dependencies as this version is no longer maintained an may contain bugs and security issues.
[0] npm WARN deprecated apollo-tracing@0.16.0: The `apollo-tracing` package is no longer part of Apollo Server 3. See https://www.apollographql.com/docs/apollo-server/migration/#tracing for details
[0] npm WARN deprecated source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated
[0] npm WARN deprecated accept@3.1.3: This module has moved and is now available at @hapi/accept. Please update your dependencies as this version is no longer maintained an may contain bugs and security issues.
[0] npm WARN deprecated apollo-server-plugin-base@0.14.0: The `apollo-server-plugin-base` package is part of Apollo Server v2 and v3, which are now deprecated (end-of-life October 22nd 2023 and October 22nd 2024, respectively). This package's functionality is now found in the `@apollo/server` package. See https://www.apollographql.com/docs/apollo-server/previous-versions/ for more details.
[0] npm WARN deprecated apollo-server-plugin-base@0.14.0: The `apollo-server-plugin-base` package is part of Apollo Server v2 and v3, which are now deprecated (end-of-life October 22nd 2023 and October 22nd 2024, respectively). This package's functionality is now found in the `@apollo/server` package. See https://www.apollographql.com/docs/apollo-server/previous-versions/ for more details.
[0] npm WARN deprecated apollo-server-plugin-base@0.14.0: The `apollo-server-plugin-base` package is part of Apollo Server v2 and v3, which are now deprecated (end-of-life October 22nd 2023 and October 22nd 2024, respectively). This package's functionality is now found in the `@apollo/server` package. See https://www.apollographql.com/docs/apollo-server/previous-versions/ for more details.
[0] npm WARN deprecated apollo-server-types@0.10.0: The `apollo-server-types` package is part of Apollo Server v2 and v3, which are now deprecated (end-of-life October 22nd 2023 and October 22nd 2024, respectively). This package's functionality is now found in the `@apollo/server` package. See https://www.apollographql.com/docs/apollo-server/previous-versions/ for more details.
[0] npm WARN deprecated apollo-server-types@0.10.0: The `apollo-server-types` package is part of Apollo Server v2 and v3, which are now deprecated (end-of-life October 22nd 2023 and October 22nd 2024, respectively). This package's functionality is now found in the `@apollo/server` package. See https://www.apollographql.com/docs/apollo-server/previous-versions/ for more details.
[0] npm WARN deprecated apollo-server-types@0.10.0: The `apollo-server-types` package is part of Apollo Server v2 and v3, which are now deprecated (end-of-life October 22nd 2023 and October 22nd 2024, respectively). This package's functionality is now found in the `@apollo/server` package. See https://www.apollographql.com/docs/apollo-server/previous-versions/ for more details.
[0] npm WARN deprecated apollo-server-types@0.10.0: The `apollo-server-types` package is part of Apollo Server v2 and v3, which are now deprecated (end-of-life October 22nd 2023 and October 22nd 2024, respectively). This package's functionality is now found in the `@apollo/server` package. See https://www.apollographql.com/docs/apollo-server/previous-versions/ for more details.
[0] npm WARN deprecated graphql-extensions@0.16.0: The `graphql-extensions` API has been removed from Apollo Server 3. Use the plugin API instead: https://www.apollographql.com/docs/apollo-server/integrations/plugins/
[0] npm WARN deprecated chokidar@2.1.8: Chokidar 2 does not receive security updates since 2019. Upgrade to chokidar 3 with 15x fewer dependencies
[0] npm WARN deprecated apollo-server-errors@2.5.0: The `apollo-server-errors` package is part of Apollo Server v2 and v3, which are now deprecated (end-of-life October 22nd 2023 and October 22nd 2024, respectively). This package's functionality is now found in the `@apollo/server` package. See https://www.apollographql.com/docs/apollo-server/previous-versions/ for more details.
[0] npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
[0] npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
[0] npm WARN deprecated apollo-cache-control@0.15.0: The functionality provided by the `apollo-cache-control` package is built in to `apollo-server-core` starting with Apollo Server 3. See https://www.apollographql.com/docs/apollo-server/migration/#cachecontrol for details.
[0] npm WARN deprecated apollo-server-caching@0.7.0: This package is part of the legacy caching implementation used by Apollo Server v2 and v3, and is no longer maintained. We recommend you switch to the newer Keyv-based implementation (which is compatible with all versions of Apollo Server). See https://www.apollographql.com/docs/apollo-server/v3/performance/cache-backends#legacy-caching-implementation for more details.
[0] npm WARN deprecated apollo-server-micro@2.26.2: The `apollo-server-micro` package is part of Apollo Server v2 and v3, which are now deprecated (end-of-life October 22nd 2023 and October 22nd 2024, respectively). This package's functionality is now found in the `@apollo/server` package. See https://www.apollographql.com/docs/apollo-server/previous-versions/ for more details.
[0] npm WARN deprecated w3c-hr-time@1.0.2: Use your platform's native performance.now() and performance.timeOrigin.
[0] npm WARN deprecated apollo-reporting-protobuf@0.8.0: The `apollo-reporting-protobuf` package is part of Apollo Server v2 and v3, which are now deprecated (end-of-life October 22nd 2023 and October 22nd 2024, respectively). This package's functionality is now found in the `@apollo/usage-reporting-protobuf` package. See https://www.apollographql.com/docs/apollo-server/previous-versions/ for more details.
[0] npm WARN deprecated apollo-reporting-protobuf@0.8.0: The `apollo-reporting-protobuf` package is part of Apollo Server v2 and v3, which are now deprecated (end-of-life October 22nd 2023 and October 22nd 2024, respectively). This package's functionality is now found in the `@apollo/usage-reporting-protobuf` package. See https://www.apollographql.com/docs/apollo-server/previous-versions/ for more details.
[0] npm WARN deprecated apollo-reporting-protobuf@0.8.0: The `apollo-reporting-protobuf` package is part of Apollo Server v2 and v3, which are now deprecated (end-of-life October 22nd 2023 and October 22nd 2024, respectively). This package's functionality is now found in the `@apollo/usage-reporting-protobuf` package. See https://www.apollographql.com/docs/apollo-server/previous-versions/ for more details.
[0] npm WARN deprecated apollo-reporting-protobuf@0.8.0: The `apollo-reporting-protobuf` package is part of Apollo Server v2 and v3, which are now deprecated (end-of-life October 22nd 2023 and October 22nd 2024, respectively). This package's functionality is now found in the `@apollo/usage-reporting-protobuf` package. See https://www.apollographql.com/docs/apollo-server/previous-versions/ for more details.
[0] npm WARN deprecated sourcemap-codec@1.4.8: Please use @jridgewell/sourcemap-codec instead
[0] npm WARN deprecated apollo-server-env@3.2.0: The `apollo-server-env` package is part of Apollo Server v2 and v3, which are now deprecated (end-of-life October 22nd 2023 and October 22nd 2024, respectively). This package's functionality is now found in the `@apollo/utils.fetcher` package. See https://www.apollographql.com/docs/apollo-server/previous-versions/ for more details.
[0] npm WARN deprecated apollo-server-env@3.2.0: The `apollo-server-env` package is part of Apollo Server v2 and v3, which are now deprecated (end-of-life October 22nd 2023 and October 22nd 2024, respectively). This package's functionality is now found in the `@apollo/utils.fetcher` package. See https://www.apollographql.com/docs/apollo-server/previous-versions/ for more details.
[0] npm WARN deprecated apollo-server-env@3.2.0: The `apollo-server-env` package is part of Apollo Server v2 and v3, which are now deprecated (end-of-life October 22nd 2023 and October 22nd 2024, respectively). This package's functionality is now found in the `@apollo/utils.fetcher` package. See https://www.apollographql.com/docs/apollo-server/previous-versions/ for more details.
[0] npm WARN deprecated apollo-server-env@3.2.0: The `apollo-server-env` package is part of Apollo Server v2 and v3, which are now deprecated (end-of-life October 22nd 2023 and October 22nd 2024, respectively). This package's functionality is now found in the `@apollo/utils.fetcher` package. See https://www.apollographql.com/docs/apollo-server/previous-versions/ for more details.
[0] npm WARN deprecated rtrim@1.0.1: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
[0] npm WARN deprecated sane@4.1.0: some dependency vulnerabilities fixed, support for node < 10 dropped, and newer ECMAScript syntax/features added
[0] npm WARN deprecated redux-devtools-extension@2.13.9: Package moved to @redux-devtools/extension.
[0] npm WARN deprecated workbox-cacheable-response@6.6.0: workbox-background-sync@6.6.0
[0] npm WARN deprecated querystring@0.2.1: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
[0] npm WARN deprecated phin@2.9.3: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
[0] npm WARN deprecated workbox-google-analytics@6.6.0: It is not compatible with newer versions of GA starting with v4, as long as you are using GAv3 it should be ok, but the package is not longer being maintained
[0] npm WARN deprecated subscriptions-transport-ws@0.9.19: The `subscriptions-transport-ws` package is no longer maintained. We recommend you use `graphql-ws` instead. For help migrating Apollo software to `graphql-ws`, see https://www.apollographql.com/docs/apollo-server/data/subscriptions/#switching-from-subscriptions-transport-ws    For general help using `graphql-ws`, see https://github.com/enisdenjo/graphql-ws/blob/master/README.md
[0] npm WARN deprecated multibase@4.0.6: This module has been superseded by the multiformats module
[0] npm WARN deprecated formidable@1.2.6: Please upgrade to latest, formidable@v2 or formidable@v3! Check these notes: https://bit.ly/2ZEqIau
[0] npm WARN deprecated domexception@2.0.1: Use your platform's native DOMException instead
[0] npm WARN deprecated apollo-server-errors@3.3.1: The `apollo-server-errors` package is part of Apollo Server v2 and v3, which are now deprecated (end-of-life October 22nd 2023 and October 22nd 2024, respectively). This package's functionality is now found in the `@apollo/server` package. See https://www.apollographql.com/docs/apollo-server/previous-versions/ for more details.
[0] npm WARN deprecated apollo-server-types@3.8.0: The `apollo-server-types` package is part of Apollo Server v2 and v3, which are now deprecated (end-of-life October 22nd 2023 and October 22nd 2024, respectively). This package's functionality is now found in the `@apollo/server` package. See https://www.apollographql.com/docs/apollo-server/previous-versions/ for more details.
[0] npm WARN deprecated apollo-server-plugin-base@3.7.2: The `apollo-server-plugin-base` package is part of Apollo Server v2 and v3, which are now deprecated (end-of-life October 22nd 2023 and October 22nd 2024, respectively). This package's functionality is now found in the `@apollo/server` package. See https://www.apollographql.com/docs/apollo-server/previous-versions/ for more details.
[0] npm WARN deprecated apollo-datasource@3.3.2: The `apollo-datasource` package is part of Apollo Server v2 and v3, which are now deprecated (end-of-life October 22nd 2023 and October 22nd 2024, respectively). See https://www.apollographql.com/docs/apollo-server/previous-versions/ for more details.
[0] npm WARN deprecated abab@2.0.6: Use your platform's native atob() and btoa() methods instead
[0] npm WARN deprecated acorn-dynamic-import@2.0.2: This is probably built in to whatever tool you're using. If you still need it... idk
[0] npm WARN deprecated apollo-server-env@4.2.1: The `apollo-server-env` package is part of Apollo Server v2 and v3, which are now deprecated (end-of-life October 22nd 2023 and October 22nd 2024, respectively). This package's functionality is now found in the `@apollo/utils.fetcher` package. See https://www.apollographql.com/docs/apollo-server/previous-versions/ for more details.
[0] npm WARN deprecated apollo-reporting-protobuf@3.4.0: The `apollo-reporting-protobuf` package is part of Apollo Server v2 and v3, which are now deprecated (end-of-life October 22nd 2023 and October 22nd 2024, respectively). This package's functionality is now found in the `@apollo/usage-reporting-protobuf` package. See https://www.apollographql.com/docs/apollo-server/previous-versions/ for more details.
[0] npm WARN deprecated ipfs-core-utils@0.18.1: js-IPFS has been deprecated in favour of Helia - please see https://github.com/ipfs/js-ipfs/issues/4336 for details
[0] npm WARN deprecated graphql-tools@4.0.8: This package has been deprecated and now it only exports makeExecutableSchema.
[0] npm WARN deprecated And it will no longer receive updates.
[0] npm WARN deprecated We recommend you to migrate to scoped packages such as @graphql-tools/schema, @graphql-tools/utils and etc.
npm WARN deprecated Check out https://www.graphql-tools.com to learn what package you should use instead
[0] npm WARN deprecated ipfs-core-config@0.7.1: js-IPFS has been deprecated in favour of Helia - please see https://github.com/ipfs/js-ipfs/issues/4336 for details
[0] npm WARN deprecated apollo-server-core@2.26.2: The `apollo-server-core` package is part of Apollo Server v2 and v3, which are now deprecated (end-of-life October 22nd 2023 and October 22nd 2024, respectively). This package's functionality is now found in the `@apollo/server` package. See https://www.apollographql.com/docs/apollo-server/previous-versions/ for more details.
[0] npm WARN deprecated ipfs-core-types@0.14.1: js-IPFS has been deprecated in favour of Helia - please see https://github.com/ipfs/js-ipfs/issues/4336 for details
[0] npm WARN deprecated xterm@5.3.0: This package is now deprecated. Move to @xterm/xterm instead.
[0] npm WARN deprecated ipfs-http-client@60.0.1: js-IPFS has been deprecated in favour of Helia - please see https://github.com/ipfs/js-ipfs/issues/4336 for details
[0] npm WARN deprecated ipfs-core@0.18.1: js-IPFS has been deprecated in favour of Helia - please see https://github.com/ipfs/js-ipfs/issues/4336 for details
[0] npm WARN tarball tarball data for three-bmfont-text@git+ssh://git@github.com/dmarcos/three-bmfont-text.git#eed4878795be9b3e38cf6aec6b903f56acd1f695 (sha512-FDlyR8SyHQ0Ek38qBx5Hg/AwPuBI/1w/QWpMgzw19Vn81xsDNFTOXJpU0HcvI78C72wwXjJ3T7+EX7k2geDV4Q==) seems to be corrupted. Trying again.
[0] npm WARN deprecated @babel/plugin-proposal-optional-chaining@7.21.0: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-optional-chaining instead.
[0] npm WARN deprecated @babel/plugin-proposal-nullish-coalescing-operator@7.18.6: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-nullish-coalescing-operator instead.
[0] npm WARN deprecated @babel/plugin-proposal-optional-catch-binding@7.18.6: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-optional-catch-binding instead.
[0] npm WARN deprecated @babel/plugin-proposal-numeric-separator@7.18.6: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-numeric-separator instead.
[0] npm WARN deprecated @babel/plugin-proposal-logical-assignment-operators@7.20.7: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-logical-assignment-operators instead.
[0] npm WARN deprecated @babel/plugin-proposal-async-generator-functions@7.20.7: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-async-generator-functions instead.
[0] npm WARN deprecated @babel/plugin-proposal-class-properties@7.18.6: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-class-properties instead.
[0] npm WARN deprecated @babel/plugin-proposal-object-rest-spread@7.20.7: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-object-rest-spread instead.
[0] npm WARN deprecated rollup-plugin-terser@7.0.2: This package has been deprecated and is no longer maintained. Please use @rollup/plugin-terser
[0] npm WARN tarball tarball data for three-bmfont-text@git+ssh://git@github.com/dmarcos/three-bmfont-text.git#eed4878795be9b3e38cf6aec6b903f56acd1f695 (sha512-FDlyR8SyHQ0Ek38qBx5Hg/AwPuBI/1w/QWpMgzw19Vn81xsDNFTOXJpU0HcvI78C72wwXjJ3T7+EX7k2geDV4Q==) seems to be corrupted. Trying again.
[0] npm WARN deprecated @belivvr/aframe-react@0.4.2: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
[0] npm WARN deprecated core-js@2.6.12: core-js@<3.23.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Some versions have web compatibility issues. Please, upgrade your dependencies to the actual version of core-js.
[0] npm ERR! code EINTEGRITY
[0] npm ERR! sha512-FDlyR8SyHQ0Ek38qBx5Hg/AwPuBI/1w/QWpMgzw19Vn81xsDNFTOXJpU0HcvI78C72wwXjJ3T7+EX7k2geDV4Q== integrity checksum failed when using sha512: wanted sha512-FDlyR8SyHQ0Ek38qBx5Hg/AwPuBI/1w/QWpMgzw19Vn81xsDNFTOXJpU0HcvI78C72wwXjJ3T7+EX7k2geDV4Q== but got sha512-JcaccaRCcK/A4c0igPQ9RCw91cil7pLhogDVmrThEvP20B/vbFaaNlmn3frF7pWeo3lATUiNrxVfgxm9qfr9GA==. (7597 bytes)
[0] 
[0] npm ERR! A complete log of this run can be found in:
[0] npm ERR!     /home/gitpod/.npm/_logs/2024-05-26T03_53_35_467Z-debug.log
[0] echo "packages/hasura npm ci" && cd /workspace/empty/dev/packages/hasura && npm ci && cd ../.. && echo "packages/sdk npm ci" && cd /workspace/empty/dev/packages/sdk && npm ci && cd ../.. && echo "packages/gh-pages npm ci" && cd /workspace/empty/dev/packages/gh-pages && npm ci && cd ../.. && echo "packages/materialized-path npm ci" && cd /workspace/empty/dev/packages/materialized-path && npm ci && cd ../.. && echo "packages/store npm ci" && cd /workspace/empty/dev/packages/store && npm ci && cd ../.. && echo "packages/react-hasura npm ci" && cd /workspace/empty/dev/packages/react-hasura && npm ci && cd ../.. && echo "packages/js-docker-isolation-provider npm ci" && cd /workspace/empty/dev/packages/js-docker-isolation-provider && npm ci && cd ../.. && echo "packages/npm-packager npm ci" && cd /workspace/empty/dev/packages/npm-packager && npm ci && cd ../.. && echo "packages/deep-memo-app npm ci" && cd /workspace/empty/dev/packages/deep-memo-app && npm ci && cd ../.. && echo "packages/deep-memo npm ci" && cd /workspace/empty/dev/packages/deep-memo && npm ci exited with code 1
[03:53:35] 'packages:ci' errored after 1.87 min
[03:53:35] Error: [object Object]
    at formatError (/workspace/empty/dev/node_modules/gulp-cli/lib/versioned/^4.0.0/format-error.js:21:10)
    at Gulp.<anonymous> (/workspace/empty/dev/node_modules/gulp-cli/lib/versioned/^4.0.0/log/events.js:33:15)
    at Gulp.emit (node:events:531:35)
    at Gulp.emit (node:domain:488:12)
    at Object.error (/workspace/empty/dev/node_modules/undertaker/lib/helpers/createExtensions.js:61:10)
    at handler (/workspace/empty/dev/node_modules/now-and-later/lib/map.js:50:14)
    at f (/workspace/empty/dev/node_modules/once/once.js:25:25)
    at f (/workspace/empty/dev/node_modules/once/once.js:25:25)
    at tryCatch (/workspace/empty/dev/node_modules/async-done/index.js:24:15)
    at done (/workspace/empty/dev/node_modules/async-done/index.js:40:12)
```

**Comment by Konard** [comment]
Duplicate of https://github.com/deep-foundation/dev/issues/232
