### ISSUE TITLE
`npm run local` fails with [1] Error: DeepClient Select Error: field "links" not found in type: 'query_root'

### ISSUE THREAD

**Issue by Konard** [deep-foundation/dev#237]
[local.log.txt](https://github.com/deep-foundation/dev/files/15446166/local.log.txt)

[local.log 2.txt](https://github.com/deep-foundation/dev/files/15446465/local.log.2.txt)

```
[1] [HPM] Rewriting path from "/gql" to "/v1/graphql"
[1] [HPM] POST /gql ~> http://localhost:8080
[1] {
[1]   query: {
[1]     query: { kind: 'Document', definitions: [Array], loc: [Object] },
[1]     variables: { where0: [Object] },
[1]     queryString: 'query SELECT ($distinct_on0: [links_select_column!],$limit0: Int,$offset0: Int,$order_by0: [links_order_by!],$where0: links_bool_exp!) { q0: links(distinct_on: $distinct_on0,limit: $limit0,offset: $offset0,order_by: $order_by0,where: $where0) { id type_id from_id to_id value } }'
[1]   },
[1]   queryData: [Function (anonymous)]
[1] }
[1] file:///workspace/empty/dev/packages/deeplinks/imports/client.js:544
[1]                 throw new Error(`DeepClient Select Error: ${e.message}`, { cause: e });
[1]                       ^
[1] 
[1] Error: DeepClient Select Error: field "links" not found in type: 'query_root'
[1]     at DeepClient.<anonymous> (file:///workspace/empty/dev/packages/deeplinks/imports/client.js:544:23)
[1]     at Generator.throw (<anonymous>)
[1]     at rejected (file:///workspace/empty/dev/packages/deeplinks/imports/client.js:5:65)
[1]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
[1]   [cause]: ApolloError: field "links" not found in type: 'query_root'
[1]       at new ApolloError (/workspace/empty/dev/node_modules/@apollo/client/errors/errors.cjs:33:28)
[1]       at /workspace/empty/dev/node_modules/@apollo/client/core/core.cjs:1996:47
[1]       at both (/workspace/empty/dev/node_modules/@apollo/client/utilities/utilities.cjs:1352:31)
[1]       at /workspace/empty/dev/node_modules/@apollo/client/utilities/utilities.cjs:1343:72
[1]       at new Promise (<anonymous>)
[1]       at Object.then (/workspace/empty/dev/node_modules/@apollo/client/utilities/utilities.cjs:1343:24)
[1]       at Object.next (/workspace/empty/dev/node_modules/@apollo/client/utilities/utilities.cjs:1354:49)
[1]       at notifySubscription (/workspace/empty/dev/node_modules/zen-observable/lib/Observable.js:135:18)
[1]       at onNotify (/workspace/empty/dev/node_modules/zen-observable/lib/Observable.js:179:3)
[1]       at SubscriptionObserver.next (/workspace/empty/dev/node_modules/zen-observable/lib/Observable.js:235:7) {
[1]     graphQLErrors: [
[1]       {
[1]         extensions: { path: '$.selectionSet.links', code: 'validation-failed' },
[1]         message: `field "links" not found in type: 'query_root'`
[1]       }
[1]     ],
[1]     protocolErrors: [],
[1]     clientErrors: [],
[1]     networkError: null,
[1]     extraInfo: undefined
[1]   }
[1] }
[1] 
[1] Node.js v20.13.1
[1] npm run deeplinks exited with code 1
```

**Comment by Konard** [comment]
Error message is updated?

```
[1] [HPM] Rewriting path from "/gql" to "/v1/graphql"
[1] [HPM] POST /gql ~> http://localhost:8080
[1] [HPM] Rewriting path from "/gql" to "/v1/graphql"
[1] [HPM] POST /gql ~> http://localhost:8080
[1] {
[1]   query: {
[1]     query: { kind: 'Document', definitions: [Array], loc: [Object] },
[1]     variables: { where0: [Object] },
[1]     queryString: 'query SELECT ($distinct_on0: [links_select_column!],$limit0: Int,$offset0: Int,$order_by0: [links_order_by!],$where0: links_bool_exp!) { q0: links(distinct_on: $distinct_on0,limit: $limit0,offset: $offset0,order_by: $order_by0,where: $where0) { id type_id from_id to_id value } }'
[1]   },
[1]   queryData: [Function (anonymous)]
[1] }
[1] file:///workspace/empty/dev/packages/deeplinks/imports/client.js:544
[1]                 throw new Error(`DeepClient Select Error: ${e.message}`, { cause: e });
[1]                       ^
[1] 
[1] Error: DeepClient Select Error: field "links" not found in type: 'query_root'
[1]     at DeepClient.<anonymous> (file:///workspace/empty/dev/packages/deeplinks/imports/client.js:544:23)
[1]     at Generator.throw (<anonymous>)
[1]     at rejected (file:///workspace/empty/dev/packages/deeplinks/imports/client.js:5:65)
[1]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
[1]   [cause]: ApolloError: field "links" not found in type: 'query_root'
[1]       at new ApolloError (/workspace/empty/dev/node_modules/@apollo/client/errors/errors.cjs:33:28)
[1]       at /workspace/empty/dev/node_modules/@apollo/client/core/core.cjs:1996:47
[1]       at both (/workspace/empty/dev/node_modules/@apollo/client/utilities/utilities.cjs:1352:31)
[1]       at /workspace/empty/dev/node_modules/@apollo/client/utilities/utilities.cjs:1343:72
[1]       at new Promise (<anonymous>)
[1]       at Object.then (/workspace/empty/dev/node_modules/@apollo/client/utilities/utilities.cjs:1343:24)
[1]       at Object.next (/workspace/empty/dev/node_modules/@apollo/client/utilities/utilities.cjs:1354:49)
[1]       at notifySubscription (/workspace/empty/dev/node_modules/zen-observable/lib/Observable.js:135:18)
[1]       at onNotify (/workspace/empty/dev/node_modules/zen-observable/lib/Observable.js:179:3)
[1]       at SubscriptionObserver.next (/workspace/empty/dev/node_modules/zen-observable/lib/Observable.js:235:7) {
[1]     graphQLErrors: [
[1]       {
[1]         extensions: { path: '$.selectionSet.links', code: 'validation-failed' },
[1]         message: `field "links" not found in type: 'query_root'`
[1]       }
[1]     ],
[1]     protocolErrors: [],
[1]     clientErrors: [],
[1]     networkError: null,
[1]     extraInfo: undefined
[1]   }
[1] }
[1] 
[1] Node.js v20.13.1
[1] npm run deeplinks exited with code 1
```

**Comment by Konard** [comment]
Error message is updated:

```
[1] {
[1]   queryData: {
[1]     query: {
[1]       query: {
[1]         kind: 'Document',
[1]         definitions: [
[1]           {
[1]             kind: 'OperationDefinition',
[1]             operation: 'query',
[1]             name: { kind: 'Name', value: 'SELECT' },
[1]             variableDefinitions: [
[1]               {
[1]                 kind: 'VariableDefinition',
[1]                 variable: {
[1]                   kind: 'Variable',
[1]                   name: { kind: 'Name', value: 'distinct_on0' }
[1]                 },
[1]                 type: {
[1]                   kind: 'ListType',
[1]                   type: {
[1]                     kind: 'NonNullType',
[1]                     type: {
[1]                       kind: 'NamedType',
[1]                       name: { kind: 'Name', value: 'links_select_column' }
[1]                     }
[1]                   }
[1]                 },
[1]                 defaultValue: undefined,
[1]                 directives: []
[1]               },
[1]               {
[1]                 kind: 'VariableDefinition',
[1]                 variable: {
[1]                   kind: 'Variable',
[1]                   name: { kind: 'Name', value: 'limit0' }
[1]                 },
[1]                 type: {
[1]                   kind: 'NamedType',
[1]                   name: { kind: 'Name', value: 'Int' }
[1]                 },
[1]                 defaultValue: undefined,
[1]                 directives: []
[1]               },
[1]               {
[1]                 kind: 'VariableDefinition',
[1]                 variable: {
[1]                   kind: 'Variable',
[1]                   name: { kind: 'Name', value: 'offset0' }
[1]                 },
[1]                 type: {
[1]                   kind: 'NamedType',
[1]                   name: { kind: 'Name', value: 'Int' }
[1]                 },
[1]                 defaultValue: undefined,
[1]                 directives: []
[1]               },
[1]               {
[1]                 kind: 'VariableDefinition',
[1]                 variable: {
[1]                   kind: 'Variable',
[1]                   name: { kind: 'Name', value: 'order_by0' }
[1]                 },
[1]                 type: {
[1]                   kind: 'ListType',
[1]                   type: {
[1]                     kind: 'NonNullType',
[1]                     type: {
[1]                       kind: 'NamedType',
[1]                       name: { kind: 'Name', value: 'links_order_by' }
[1]                     }
[1]                   }
[1]                 },
[1]                 defaultValue: undefined,
[1]                 directives: []
[1]               },
[1]               {
[1]                 kind: 'VariableDefinition',
[1]                 variable: {
[1]                   kind: 'Variable',
[1]                   name: { kind: 'Name', value: 'where0' }
[1]                 },
[1]                 type: {
[1]                   kind: 'NonNullType',
[1]                   type: {
[1]                     kind: 'NamedType',
[1]                     name: { kind: 'Name', value: 'links_bool_exp' }
[1]                   }
[1]                 },
[1]                 defaultValue: undefined,
[1]                 directives: []
[1]               }
[1]             ],
[1]             directives: [],
[1]             selectionSet: {
[1]               kind: 'SelectionSet',
[1]               selections: [
[1]                 {
[1]                   kind: 'Field',
[1]                   alias: { kind: 'Name', value: 'q0' },
[1]                   name: { kind: 'Name', value: 'links' },
[1]                   arguments: [
[1]                     {
[1]                       kind: 'Argument',
[1]                       name: { kind: 'Name', value: 'distinct_on' },
[1]                       value: {
[1]                         kind: 'Variable',
[1]                         name: { kind: 'Name', value: 'distinct_on0' }
[1]                       }
[1]                     },
[1]                     {
[1]                       kind: 'Argument',
[1]                       name: { kind: 'Name', value: 'limit' },
[1]                       value: {
[1]                         kind: 'Variable',
[1]                         name: { kind: 'Name', value: 'limit0' }
[1]                       }
[1]                     },
[1]                     {
[1]                       kind: 'Argument',
[1]                       name: { kind: 'Name', value: 'offset' },
[1]                       value: {
[1]                         kind: 'Variable',
[1]                         name: { kind: 'Name', value: 'offset0' }
[1]                       }
[1]                     },
[1]                     {
[1]                       kind: 'Argument',
[1]                       name: { kind: 'Name', value: 'order_by' },
[1]                       value: {
[1]                         kind: 'Variable',
[1]                         name: { kind: 'Name', value: 'order_by0' }
[1]                       }
[1]                     },
[1]                     {
[1]                       kind: 'Argument',
[1]                       name: { kind: 'Name', value: 'where' },
[1]                       value: {
[1]                         kind: 'Variable',
[1]                         name: { kind: 'Name', value: 'where0' }
[1]                       }
[1]                     }
[1]                   ],
[1]                   directives: [],
[1]                   selectionSet: {
[1]                     kind: 'SelectionSet',
[1]                     selections: [
[1]                       {
[1]                         kind: 'Field',
[1]                         alias: undefined,
[1]                         name: { kind: 'Name', value: 'id' },
[1]                         arguments: [],
[1]                         directives: [],
[1]                         selectionSet: undefined
[1]                       },
[1]                       {
[1]                         kind: 'Field',
[1]                         alias: undefined,
[1]                         name: { kind: 'Name', value: 'type_id' },
[1]                         arguments: [],
[1]                         directives: [],
[1]                         selectionSet: undefined
[1]                       },
[1]                       {
[1]                         kind: 'Field',
[1]                         alias: undefined,
[1]                         name: { kind: 'Name', value: 'from_id' },
[1]                         arguments: [],
[1]                         directives: [],
[1]                         selectionSet: undefined
[1]                       },
[1]                       {
[1]                         kind: 'Field',
[1]                         alias: undefined,
[1]                         name: { kind: 'Name', value: 'to_id' },
[1]                         arguments: [],
[1]                         directives: [],
[1]                         selectionSet: undefined
[1]                       },
[1]                       {
[1]                         kind: 'Field',
[1]                         alias: undefined,
[1]                         name: { kind: 'Name', value: 'value' },
[1]                         arguments: [],
[1]                         directives: [],
[1]                         selectionSet: undefined
[1]                       }
[1]                     ]
[1]                   }
[1]                 }
[1]               ]
[1]             }
[1]           }
[1]         ],
[1]         loc: Location {
[1]           start: 0,
[1]           end: 279,
[1]           source: Source {
[1]             body: 'query SELECT ($distinct_on0: [links_select_column!],$limit0: Int,$offset0: Int,$order_by0: [links_order_by!],$where0: links_bool_exp!) { q0: links(distinct_on: $distinct_on0,limit: $limit0,offset: $offset0,order_by: $order_by0,where: $where0) { id type_id from_id to_id value } }',
[1]             name: 'GraphQL request',
[1]             locationOffset: { line: 1, column: 1 }
[1]           }
[1]         }
[1]       },
[1]       variables: { where0: { type_id: { _eq: 163 } } },
[1]       queryString: 'query SELECT ($distinct_on0: [links_select_column!],$limit0: Int,$offset0: Int,$order_by0: [links_order_by!],$where0: links_bool_exp!) { q0: links(distinct_on: $distinct_on0,limit: $limit0,offset: $offset0,order_by: $order_by0,where: $where0) { id type_id from_id to_id value } }'
[1]     },
[1]     queryData: [Function (anonymous)]
[1]   }
[1] }
[1] file:///workspace/empty/dev/packages/deeplinks/imports/client.js:544
[1]                 throw new Error(`DeepClient Select Error: ${e.message}`, { cause: e });
[1]                       ^
[1] 
[1] Error: DeepClient Select Error: field "links" not found in type: 'query_root'
[1]     at DeepClient.<anonymous> (file:///workspace/empty/dev/packages/deeplinks/imports/client.js:544:23)
[1]     at Generator.throw (<anonymous>)
[1]     at rejected (file:///workspace/empty/dev/packages/deeplinks/imports/client.js:5:65)
[1]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
[1]   [cause]: ApolloError: field "links" not found in type: 'query_root'
[1]       at new ApolloError (/workspace/empty/dev/node_modules/@apollo/client/errors/errors.cjs:33:28)
[1]       at /workspace/empty/dev/node_modules/@apollo/client/core/core.cjs:1996:47
[1]       at both (/workspace/empty/dev/node_modules/@apollo/client/utilities/utilities.cjs:1352:31)
[1]       at /workspace/empty/dev/node_modules/@apollo/client/utilities/utilities.cjs:1343:72
[1]       at new Promise (<anonymous>)
[1]       at Object.then (/workspace/empty/dev/node_modules/@apollo/client/utilities/utilities.cjs:1343:24)
[1]       at Object.next (/workspace/empty/dev/node_modules/@apollo/client/utilities/utilities.cjs:1354:49)
[1]       at notifySubscription (/workspace/empty/dev/node_modules/zen-observable/lib/Observable.js:135:18)
[1]       at onNotify (/workspace/empty/dev/node_modules/zen-observable/lib/Observable.js:179:3)
[1]       at SubscriptionObserver.next (/workspace/empty/dev/node_modules/zen-observable/lib/Observable.js:235:7) {
[1]     graphQLErrors: [
[1]       {
[1]         extensions: { path: '$.selectionSet.links', code: 'validation-failed' },
[1]         message: `field "links" not found in type: 'query_root'`
[1]       }
[1]     ],
[1]     protocolErrors: [],
[1]     clientErrors: [],
[1]     networkError: null,
[1]     extraInfo: undefined
[1]   }
[1] }
[1] 
[1] Node.js v20.13.1
[1] npm run deeplinks exited with code 1
```

**Comment by Konard** [comment]
> [1]       variables: { where0: { type_id: { _eq: 163 } } },

Means it is `HandleGql` type from `@deep-foundation/core` package.

So the issue is with change in https://github.com/deep-foundation/deeplinks/commit/4295ccbc7d2ea9d147edee2c4791daecfa536b8a commit.

https://github.com/deep-foundation/deeplinks/commit/4295ccbc7d2ea9d147edee2c4791daecfa536b8a#diff-208c8f493c5bace0d38977fa3c256662926c299013249b884d503bf94fcdcabaR798-R812

https://github.com/deep-foundation/deeplinks/blob/0dd9bd044c4a043809addfde4d6dcba4848c8e28/imports/router/links.ts#L807-L821

Specifically with `handleGqlLinks` function.

This function should ignore the error.
