### ISSUE TITLE
certbot: ModuleNotFoundError: No module named 'six'

### ISSUE THREAD

**Issue by Konard** [deep-foundation/dev#238]
```
rroot@vds2441251:~/nginx# node configure-nginx.js --configurations "$DEEPCASE_HOST 3007" "$DEEPLINKS_HOST 3006" --certbot-email drakonard@gmail.com
Executing: sudo apt-get update && sudo apt-get install -y nginx certbot ...
Get:1 http://security.ubuntu.com/ubuntu focal-security InRelease [128 kB]
Get:2 http://ppa.launchpad.net/deadsnakes/ppa/ubuntu focal InRelease [18.1 kB]
Get:3 http://mirrors.ubuntu.com/mirrors.txt Mirrorlist [380 B]                                                           
Get:5 http://mirrors.powernet.com.ru/ubuntu focal-updates InRelease [128 kB]                                                                   
Get:7 http://ppa.launchpad.net/deadsnakes/ppa/ubuntu focal/main amd64 Packages [30.0 kB]                                                       
Get:8 http://ppa.launchpad.net/deadsnakes/ppa/ubuntu focal/main i386 Packages [14.7 kB]                                                              
Hit:4 https://mirror.neftm.ru/ubuntu focal InRelease                                                                                          
Get:9 http://security.ubuntu.com/ubuntu focal-security/main amd64 Packages [2,956 kB]                                                         
Get:10 http://security.ubuntu.com/ubuntu focal-security/main i386 Packages [756 kB]
Get:11 http://security.ubuntu.com/ubuntu focal-security/main Translation-en [444 kB]
Get:6 https://mirror.truenetwork.ru/ubuntu focal-backports InRelease [128 kB]        
Get:12 http://security.ubuntu.com/ubuntu focal-security/restricted i386 Packages [36.4 kB]      
Get:13 http://security.ubuntu.com/ubuntu focal-security/restricted amd64 Packages [2,837 kB]
Ign:15 http://mirror.corbina.net/ubuntu focal-updates/main amd64 Packages                     
Get:21 http://mirrors.powernet.com.ru/ubuntu focal-updates/universe amd64 Packages [1,189 kB]                                                        
Get:14 http://mirror.timeweb.ru/ubuntu focal-updates/main i386 Packages [980 kB]                                                                     
Get:17 http://mirror.corbina.net/ubuntu focal-updates/restricted amd64 Packages [2,953 kB]                                                           
Get:16 http://mirror.docker.ru/ubuntu focal-updates/main Translation-en [525 kB]                                                                     
Get:25 http://security.ubuntu.com/ubuntu focal-security/restricted Translation-en [397 kB]                                                           
Get:26 http://security.ubuntu.com/ubuntu focal-security/universe amd64 Packages [963 kB]                                                             
Get:27 http://security.ubuntu.com/ubuntu focal-security/universe i386 Packages [659 kB]                                                              
Get:28 http://security.ubuntu.com/ubuntu focal-security/universe Translation-en [203 kB]                                                             
Get:29 http://security.ubuntu.com/ubuntu focal-security/multiverse amd64 Packages [24.0 kB]                                                          
Get:19 https://mirror.truenetwork.ru/ubuntu focal-updates/restricted Translation-en [413 kB]                                                         
Get:30 http://security.ubuntu.com/ubuntu focal-security/multiverse Translation-en [5,904 B]                                                          
Get:24 http://archive.ubuntu.com/ubuntu focal-updates/multiverse Translation-en [7,880 B]                                                            
Get:23 http://mirror.docker.ru/ubuntu focal-updates/multiverse amd64 Packages [26.2 kB]                                                              
Get:18 https://mirror.hyperdedic.ru/ubuntu focal-updates/restricted i386 Packages [37.7 kB]                                                          
Get:22 http://mirrors.powernet.com.ru/ubuntu focal-updates/universe Translation-en [285 kB]                                                          
Get:20 https://mirror.truenetwork.ru/ubuntu focal-updates/universe i386 Packages [786 kB]                                                            
Get:15 http://mirror.timeweb.ru/ubuntu focal-updates/main amd64 Packages [3,332 kB]                                                                  
Fetched 20.3 MB in 4s (4,768 kB/s)                                                                                                   
Reading package lists... Done
Reading package lists... Done
Building dependency tree       
Reading state information... Done
nginx is already the newest version (1.18.0-0ubuntu1.4).
certbot is already the newest version (0.40.0-1ubuntu0.1).
The following packages were automatically installed and are no longer required:
  libstd-rust-1.70 linux-headers-5.4.0-29 linux-headers-5.4.0-29-generic linux-image-5.4.0-29-generic linux-modules-5.4.0-29-generic
  linux-modules-extra-5.4.0-29-generic
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 52 not upgraded.
Executing: sudo touch /etc/nginx/sites-available/deep ...
Executing: sudo chmod 777 /etc/nginx/sites-available/deep ...
Executing: sudo ln -sf /etc/nginx/sites-available/deep /etc/nginx/sites-enabled/ ...
Executing: sudo nginx -t ...
nginx: the configuration file /etc/nginx/nginx.conf syntax is ok
nginx: configuration file /etc/nginx/nginx.conf test is successful
Executing: sudo systemctl restart nginx ...
Executing: sudo certbot certonly --webroot --webroot-path=/var/www/html -d chatgpt.deep.foundation -n --agree-tos -m drakonard@gmail.com ...
Traceback (most recent call last):
  File "/usr/bin/certbot", line 11, in <module>
    load_entry_point('certbot==0.40.0', 'console_scripts', 'certbot')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 490, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2854, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2445, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2451, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3/dist-packages/certbot/main.py", line 9, in <module>
    import configobj
  File "/usr/lib/python3/dist-packages/configobj.py", line 22, in <module>
    import six
ModuleNotFoundError: No module named 'six'
Error: Command exited with code 1.                                                         
```

**Comment by Konard** [comment]
# Solution

```bash
apt --reinstall install python3-debian
apt --reinstall install python3-six
apt --reinstall install python3-certifi
apt --reinstall install python3-requests
```
