### ISSUE TITLE
TypeError: Invalid Version: silly placeDep ROOT electron@13.6.9 KEEP for: @deep-foundation/deepcase-app@0.1.0-beta.28 want: ^13.1.9

### ISSUE THREAD

**Issue by Konard** [deep-foundation/dev#240]
```
gitpod /workspace/dev (main) $ npm run gitpod-init

> @deep-foundation/dev@0.0.21 gitpod-init
> npm run gitpod-prepare && npm ci && npm run packages


> @deep-foundation/dev@0.0.21 gitpod-prepare
> npm run git-shh-to-https && sudo apt update && (yes | sudo apt install screen) && (yes | sudo apt install rsync) && (yes | sudo apt install net-tools) && screen -S docker -d -m sudo docker-up


> @deep-foundation/dev@0.0.21 git-shh-to-https
> git config --global url."https://".insteadOf git:// && git config --global url."https://github.com/".insteadOf ssh://git@github.com/

Hit:2 http://security.ubuntu.com/ubuntu jammy-security InRelease                                                  
Hit:3 https://download.docker.com/linux/ubuntu jammy InRelease                                                    
Hit:1 https://apt.llvm.org/jammy llvm-toolchain-jammy-15 InRelease                                                
Hit:4 https://ppa.launchpadcontent.net/git-core/ppa/ubuntu jammy InRelease                                        
Hit:5 https://ppa.launchpadcontent.net/ondrej/apache2/ubuntu jammy InRelease                 
Hit:6 https://ppa.launchpadcontent.net/ondrej/nginx-mainline/ubuntu jammy InRelease
Hit:7 https://ppa.launchpadcontent.net/ondrej/php/ubuntu jammy InRelease
Hit:8 http://archive.ubuntu.com/ubuntu jammy InRelease                 
Hit:9 http://archive.ubuntu.com/ubuntu jammy-updates InRelease        
Hit:10 http://archive.ubuntu.com/ubuntu jammy-backports InRelease     
Hit:11 https://packagecloud.io/github/git-lfs/ubuntu jammy InRelease  
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
143 packages can be upgraded. Run 'apt list --upgradable' to see them.
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
screen is already the newest version (4.9.0-1).
0 upgraded, 0 newly installed, 0 to remove and 143 not upgraded.
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
rsync is already the newest version (3.2.7-0ubuntu0.22.04.2).
0 upgraded, 0 newly installed, 0 to remove and 143 not upgraded.
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
net-tools is already the newest version (1.60+git20181103.0eebece-1ubuntu5).
0 upgraded, 0 newly installed, 0 to remove and 143 not upgraded.
npm error Invalid Version: 
npm error A complete log of this run can be found in: /home/gitpod/.npm/_logs/2024-06-05T07_41_05_300Z-debug-0.log
```

```
0 verbose cli /home/gitpod/.nvm/versions/node/v18.17.1/bin/node /home/gitpod/.nvm/versions/node/v18.17.1/bin/npm
1 info using npm@10.8.1
2 info using node@v18.17.1
3 silly config load:file:/home/gitpod/.nvm/versions/node/v18.17.1/lib/node_modules/npm/npmrc
4 silly config load:file:/workspace/dev/.npmrc
5 silly config load:file:/home/gitpod/.npmrc
6 silly config load:file:/home/gitpod/.nvm/versions/node/v18.17.1/etc/npmrc
7 verbose title npm ci
8 verbose argv "ci"
9 verbose logfile logs-max:10 dir:/home/gitpod/.npm/_logs/2024-06-05T07_41_05_300Z-
10 verbose logfile /home/gitpod/.npm/_logs/2024-06-05T07_41_05_300Z-debug-0.log
11 silly packumentCache heap:4345298944 maxSize:1086324736 maxEntrySize:543162368
12 silly logfile start cleaning logs, removing 1 files
13 silly logfile done cleaning log files
14 silly idealTree buildDeps
15 silly fetch manifest electron@^13.1.9
16 silly packumentCache full:https://registry.npmjs.org/electron cache-miss
17 http fetch GET 200 https://registry.npmjs.org/electron 657ms (cache miss)
18 silly packumentCache full:https://registry.npmjs.org/electron set size:undefined disposed:false
19 silly placeDep ROOT electron@13.6.9 KEEP for: @deep-foundation/deepcase-app@0.1.0-beta.28 want: ^13.1.9
20 verbose stack TypeError: Invalid Version: 
20 verbose stack     at new SemVer (/home/gitpod/.nvm/versions/node/v18.17.1/lib/node_modules/npm/node_modules/semver/classes/semver.js:38:13)
20 verbose stack     at compare (/home/gitpod/.nvm/versions/node/v18.17.1/lib/node_modules/npm/node_modules/semver/functions/compare.js:3:32)
20 verbose stack     at Object.gte (/home/gitpod/.nvm/versions/node/v18.17.1/lib/node_modules/npm/node_modules/semver/functions/gte.js:2:30)
20 verbose stack     at Node.canDedupe (/home/gitpod/.nvm/versions/node/v18.17.1/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/node.js:1081:32)
20 verbose stack     at PlaceDep.pruneDedupable (/home/gitpod/.nvm/versions/node/v18.17.1/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/place-dep.js:426:14)
20 verbose stack     at PlaceDep.pruneDedupable (/home/gitpod/.nvm/versions/node/v18.17.1/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/place-dep.js:450:16)
20 verbose stack     at new PlaceDep (/home/gitpod/.nvm/versions/node/v18.17.1/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/place-dep.js:219:12)
20 verbose stack     at #buildDepStep (/home/gitpod/.nvm/versions/node/v18.17.1/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:917:18)
20 verbose stack     at async Arborist.buildIdealTree (/home/gitpod/.nvm/versions/node/v18.17.1/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:181:7)
20 verbose stack     at async CI.exec (/home/gitpod/.nvm/versions/node/v18.17.1/lib/node_modules/npm/lib/commands/ci.js:63:5)
21 error Invalid Version: 
22 silly unfinished npm timer idealTree:buildDeps 1717573267812
23 silly unfinished npm timer idealTree:packages/deepcase-app 1717573267824
24 verbose cwd /workspace/dev
25 verbose os Linux 6.1.89-060189-generic
26 verbose node v18.17.1
27 verbose npm  v10.8.1
28 verbose exit 1
29 verbose code 1
30 error A complete log of this run can be found in: /home/gitpod/.npm/_logs/2024-06-05T07_41_05_300Z-debug-0.log
```

**Comment by Konard** [comment]
This error is liked to the change of npm version.

# Solution

```
rm -f package-lock.json
npm i
```

**Comment by Konard** [comment]
Fixed at https://github.com/deep-foundation/dev/commit/26f05a9bc8792cbdf406436f46442c2d791be6a5
